/*
 * CarhireView.java
 */

package oscar.view;

import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * The application's main frame.
 */
public class AdminView extends FrameView implements ActionListener {

    /**
     * Class constructor
     * @param app The application
     */
    public AdminView(SingleFrameApplication app) {
        super(app);

        // init netbeans generated vars
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        tabPanel = new javax.swing.JTabbedPane();
        startPanel = new javax.swing.JPanel();
        staffPanel = new javax.swing.JPanel();
        carClassSearchPanel1 = new javax.swing.JPanel();
        plateLbl2 = new javax.swing.JLabel();
        brandLbl2 = new javax.swing.JLabel();
        brandTxt2 = new javax.swing.JTextField();
        plateTxt2 = new javax.swing.JTextField();
        addBtn4 = new javax.swing.JButton();
        clearBtn4 = new javax.swing.JButton();
        bookingPanel = new javax.swing.JPanel();
        carClassSearchPanel2 = new javax.swing.JPanel();
        refCodeLbl = new javax.swing.JLabel();
        refCodeTxt = new javax.swing.JTextField();
        surnameLbl = new javax.swing.JLabel();
        surnameTxt = new javax.swing.JTextField();
        rentalDateLbl = new javax.swing.JLabel();
        returnDateLbl = new javax.swing.JLabel();
        isBookingCB = new javax.swing.JCheckBox();
        clearBtn2 = new javax.swing.JButton();
        addBtn2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        carPanel = new javax.swing.JPanel();
        carSearchPanel = new javax.swing.JPanel();
        plateLbl = new javax.swing.JLabel();
        brandLbl = new javax.swing.JLabel();
        modelLbl = new javax.swing.JLabel();
        classLbl = new javax.swing.JLabel();
        yearLbl = new javax.swing.JLabel();
        colorLbl = new javax.swing.JLabel();
        statusLbl = new javax.swing.JLabel();
        plateTxt = new javax.swing.JTextField();
        brandTxt = new javax.swing.JTextField();
        modelTxt = new javax.swing.JTextField();
        classTxt = new javax.swing.JTextField();
        yearTxt = new javax.swing.JTextField();
        colorTxt = new javax.swing.JTextField();
        statusCB = new javax.swing.JComboBox();
        addBtn3 = new javax.swing.JButton();
        clearBtn3 = new javax.swing.JButton();
        carClassPanel = new javax.swing.JPanel();
        carClassSearchPanel = new javax.swing.JPanel();
        plateLbl1 = new javax.swing.JLabel();
        brandLbl1 = new javax.swing.JLabel();
        plateTxt1 = new javax.swing.JTextField();
        brandTxt1 = new javax.swing.JTextField();
        clearBtn1 = new javax.swing.JButton();
        addBtn1 = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        usernameLbl = new javax.swing.JLabel();
        carDialog = new javax.swing.JDialog();
        saveDlgBtn = new javax.swing.JButton();
        deleteDlgBtn = new javax.swing.JButton();
        cancelDlgBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        classCB = new javax.swing.JComboBox();
        yearDlgLbl = new javax.swing.JLabel();
        modelDlgTxt = new javax.swing.JTextField();
        classDlgLbl = new javax.swing.JLabel();
        colorDlgTxt = new javax.swing.JTextField();
        yearDlgSpn = new javax.swing.JSpinner();
        colorDlgLbl = new javax.swing.JLabel();
        statusDlgCB = new javax.swing.JComboBox();
        statusDlgLbl = new javax.swing.JLabel();
        plateDlgLbl = new javax.swing.JLabel();
        plateDlgTxt = new javax.swing.JTextField();
        brandDlgLbl = new javax.swing.JLabel();
        modelDlgLbl = new javax.swing.JLabel();
        brandDlgTxt = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        serviceMonthDlgSpn = new javax.swing.JSpinner();
        milieageDlgTxt = new javax.swing.JTextField();
        mileageDlgLbl = new javax.swing.JLabel();
        branchCB = new javax.swing.JComboBox();
        branchDlgLbl = new javax.swing.JLabel();
        lastServiceMileageDlgTxt = new javax.swing.JTextField();
        lastServiceMileageDlgLbl = new javax.swing.JLabel();
        lastServiceDlgLbl = new javax.swing.JLabel();
        serviceMilesDlgLbl = new javax.swing.JLabel();
        serviceMilesDlgTxt = new javax.swing.JTextField();
        serviceMonthDlgLbl = new javax.swing.JLabel();
        carClassDialog = new javax.swing.JDialog();
        nameDlgLbl = new javax.swing.JLabel();
        nameDlgTxt = new javax.swing.JTextField();
        displayNameDlgLbl = new javax.swing.JLabel();
        displayNameDlgTxt = new javax.swing.JTextField();
        priceDlgLbl = new javax.swing.JLabel();
        priceDlgTxt = new javax.swing.JTextField();
        saveDlgBtn1 = new javax.swing.JButton();
        deleteDlgBtn1 = new javax.swing.JButton();
        cancelDlgBtn1 = new javax.swing.JButton();
        descriptionDlgLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        staffDialog = new javax.swing.JDialog();
        saveDlgBtn2 = new javax.swing.JButton();
        deleteDlgBtn2 = new javax.swing.JButton();
        cancelDlgBtn2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        staffNameDlgLbl = new javax.swing.JLabel();
        surnameDlgLbl = new javax.swing.JLabel();
        usernameDlgLbl = new javax.swing.JLabel();
        passwordDlgLbl = new javax.swing.JLabel();
        passwordPwd = new javax.swing.JPasswordField();
        usernameDlgTxt = new javax.swing.JTextField();
        surnameDlgTxt = new javax.swing.JTextField();
        staffNameDlgTxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        addressDlgTA = new javax.swing.JTextArea();
        addressDlgLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        dateOfBirthDlgLbl = new javax.swing.JLabel();
        emailDlgLbl = new javax.swing.JLabel();
        PhoneDlgLbl = new javax.swing.JLabel();
        emailDlgTxt = new javax.swing.JTextField();
        phoneDlgTxt = new javax.swing.JTextField();

        mainPanel.setName("mainPanel"); // NOI18N

        tabPanel.setName("panel"); // NOI18N

        startPanel.setName("startPanel"); // NOI18N

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(AdminView.class);
        tabPanel.addTab(resourceMap.getString("startPanel.TabConstraints.tabTitle"), startPanel); // NOI18N

        staffPanel.setName("staffPanel"); // NOI18N

        carClassSearchPanel1.setName("carClassSearchPanel1"); // NOI18N

        plateLbl2.setText(resourceMap.getString("plateLbl2.text")); // NOI18N
        plateLbl2.setName("plateLbl2"); // NOI18N

        brandLbl2.setText(resourceMap.getString("brandLbl2.text")); // NOI18N
        brandLbl2.setName("brandLbl2"); // NOI18N

        brandTxt2.setName("brandTxt2"); // NOI18N

        plateTxt2.setName("plateTxt2"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(AdminView.class, this);
        addBtn4.setAction(actionMap.get("carDialog")); // NOI18N
        addBtn4.setIcon(resourceMap.getIcon("addBtn4.icon")); // NOI18N
        addBtn4.setText(resourceMap.getString("addBtn4.text")); // NOI18N
        addBtn4.setName("addBtn4"); // NOI18N
        addBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtn4ActionPerformed(evt);
            }
        });

        clearBtn4.setIcon(resourceMap.getIcon("clearBtn4.icon")); // NOI18N
        clearBtn4.setText(resourceMap.getString("clearBtn4.text")); // NOI18N
        clearBtn4.setName("clearBtn4"); // NOI18N

        javax.swing.GroupLayout carClassSearchPanel1Layout = new javax.swing.GroupLayout(carClassSearchPanel1);
        carClassSearchPanel1.setLayout(carClassSearchPanel1Layout);
        carClassSearchPanel1Layout.setHorizontalGroup(
            carClassSearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carClassSearchPanel1Layout.createSequentialGroup()
                .addGroup(carClassSearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(carClassSearchPanel1Layout.createSequentialGroup()
                        .addGroup(carClassSearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brandLbl2)
                            .addComponent(plateLbl2))
                        .addGap(18, 18, 18)
                        .addGroup(carClassSearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brandTxt2, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(plateTxt2, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)))
                    .addComponent(clearBtn4)
                    .addComponent(addBtn4))
                .addContainerGap())
        );
        carClassSearchPanel1Layout.setVerticalGroup(
            carClassSearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carClassSearchPanel1Layout.createSequentialGroup()
                .addGroup(carClassSearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plateLbl2)
                    .addComponent(plateTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carClassSearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandLbl2)
                    .addComponent(brandTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(clearBtn4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addBtn4))
        );

        javax.swing.GroupLayout staffPanelLayout = new javax.swing.GroupLayout(staffPanel);
        staffPanel.setLayout(staffPanelLayout);
        staffPanelLayout.setHorizontalGroup(
            staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(carClassSearchPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(575, Short.MAX_VALUE))
        );
        staffPanelLayout.setVerticalGroup(
            staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(carClassSearchPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(423, Short.MAX_VALUE))
        );

        tabPanel.addTab(resourceMap.getString("staffPanel.TabConstraints.tabTitle"), staffPanel); // NOI18N

        bookingPanel.setName("bookingPanel"); // NOI18N

        carClassSearchPanel2.setName("carClassSearchPanel2"); // NOI18N

        refCodeLbl.setText(resourceMap.getString("refCodeLbl.text")); // NOI18N
        refCodeLbl.setName("refCodeLbl"); // NOI18N

        refCodeTxt.setName("refCodeTxt"); // NOI18N

        surnameLbl.setText(resourceMap.getString("surnameLbl.text")); // NOI18N
        surnameLbl.setName("surnameLbl"); // NOI18N

        surnameTxt.setName("surnameTxt"); // NOI18N

        rentalDateLbl.setText(resourceMap.getString("rentalDateLbl.text")); // NOI18N
        rentalDateLbl.setName("rentalDateLbl"); // NOI18N

        returnDateLbl.setText(resourceMap.getString("returnDateLbl.text")); // NOI18N
        returnDateLbl.setName("returnDateLbl"); // NOI18N

        isBookingCB.setText(resourceMap.getString("isBookingCB.text")); // NOI18N
        isBookingCB.setName("isBookingCB"); // NOI18N

        clearBtn2.setIcon(resourceMap.getIcon("clearBtn2.icon")); // NOI18N
        clearBtn2.setText(resourceMap.getString("clearBtn2.text")); // NOI18N
        clearBtn2.setName("clearBtn2"); // NOI18N

        addBtn2.setAction(actionMap.get("carDialog")); // NOI18N
        addBtn2.setIcon(resourceMap.getIcon("addBtn2.icon")); // NOI18N
        addBtn2.setText(resourceMap.getString("addBtn2.text")); // NOI18N
        addBtn2.setName("addBtn2"); // NOI18N

        jButton2.setIcon(resourceMap.getIcon("jButton2.icon")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        javax.swing.GroupLayout carClassSearchPanel2Layout = new javax.swing.GroupLayout(carClassSearchPanel2);
        carClassSearchPanel2.setLayout(carClassSearchPanel2Layout);
        carClassSearchPanel2Layout.setHorizontalGroup(
            carClassSearchPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carClassSearchPanel2Layout.createSequentialGroup()
                .addGroup(carClassSearchPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(carClassSearchPanel2Layout.createSequentialGroup()
                        .addGroup(carClassSearchPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(surnameLbl)
                            .addComponent(refCodeLbl))
                        .addGap(36, 36, 36)
                        .addGroup(carClassSearchPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(refCodeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(surnameTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)))
                    .addComponent(isBookingCB)
                    .addComponent(clearBtn2)
                    .addComponent(addBtn2)
                    .addComponent(jButton2)
                    .addComponent(rentalDateLbl)
                    .addComponent(returnDateLbl))
                .addGap(0, 0, 0))
        );
        carClassSearchPanel2Layout.setVerticalGroup(
            carClassSearchPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carClassSearchPanel2Layout.createSequentialGroup()
                .addGroup(carClassSearchPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refCodeLbl)
                    .addComponent(refCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carClassSearchPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surnameLbl)
                    .addComponent(surnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rentalDateLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnDateLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(isBookingCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearBtn2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addBtn2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2))
        );

        javax.swing.GroupLayout bookingPanelLayout = new javax.swing.GroupLayout(bookingPanel);
        bookingPanel.setLayout(bookingPanelLayout);
        bookingPanelLayout.setHorizontalGroup(
            bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(carClassSearchPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(514, Short.MAX_VALUE))
        );
        bookingPanelLayout.setVerticalGroup(
            bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(carClassSearchPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
        );

        tabPanel.addTab(resourceMap.getString("bookingPanel.TabConstraints.tabTitle"), bookingPanel); // NOI18N

        carPanel.setName("carPanel"); // NOI18N

        carSearchPanel.setName("carSearchPanel"); // NOI18N

        plateLbl.setText(resourceMap.getString("plateLbl.text")); // NOI18N
        plateLbl.setName("plateLbl"); // NOI18N

        brandLbl.setText(resourceMap.getString("brandLbl.text")); // NOI18N
        brandLbl.setName("brandLbl"); // NOI18N

        modelLbl.setText(resourceMap.getString("modelLbl.text")); // NOI18N
        modelLbl.setName("modelLbl"); // NOI18N

        classLbl.setText(resourceMap.getString("classLbl.text")); // NOI18N
        classLbl.setName("classLbl"); // NOI18N

        yearLbl.setText(resourceMap.getString("yearLbl.text")); // NOI18N
        yearLbl.setName("yearLbl"); // NOI18N

        colorLbl.setText(resourceMap.getString("colorLbl.text")); // NOI18N
        colorLbl.setName("colorLbl"); // NOI18N

        statusLbl.setText(resourceMap.getString("statusLbl.text")); // NOI18N
        statusLbl.setName("statusLbl"); // NOI18N

        plateTxt.setText(resourceMap.getString("plateTxt.text")); // NOI18N
        plateTxt.setName("plateTxt"); // NOI18N

        brandTxt.setText(resourceMap.getString("brandTxt.text")); // NOI18N
        brandTxt.setName("brandTxt"); // NOI18N

        modelTxt.setText(resourceMap.getString("modelTxt.text")); // NOI18N
        modelTxt.setName("modelTxt"); // NOI18N

        classTxt.setText(resourceMap.getString("classTxt.text")); // NOI18N
        classTxt.setName("classTxt"); // NOI18N

        yearTxt.setText(resourceMap.getString("yearTxt.text")); // NOI18N
        yearTxt.setName("yearTxt"); // NOI18N

        colorTxt.setText(resourceMap.getString("colorTxt.text")); // NOI18N
        colorTxt.setName("colorTxt"); // NOI18N

        statusCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        statusCB.setName("statusCB"); // NOI18N

        addBtn3.setAction(actionMap.get("carDialog")); // NOI18N
        addBtn3.setIcon(resourceMap.getIcon("addBtn3.icon")); // NOI18N
        addBtn3.setText(resourceMap.getString("addBtn3.text")); // NOI18N
        addBtn3.setName("addBtn3"); // NOI18N
        addBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtn3ActionPerformed(evt);
            }
        });

        clearBtn3.setIcon(resourceMap.getIcon("clearBtn3.icon")); // NOI18N
        clearBtn3.setText(resourceMap.getString("clearBtn3.text")); // NOI18N
        clearBtn3.setName("clearBtn3"); // NOI18N

        javax.swing.GroupLayout carSearchPanelLayout = new javax.swing.GroupLayout(carSearchPanel);
        carSearchPanel.setLayout(carSearchPanelLayout);
        carSearchPanelLayout.setHorizontalGroup(
            carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carSearchPanelLayout.createSequentialGroup()
                .addGroup(carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(carSearchPanelLayout.createSequentialGroup()
                        .addGroup(carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brandLbl)
                            .addComponent(plateLbl)
                            .addComponent(modelLbl)
                            .addComponent(classLbl)
                            .addComponent(yearLbl)
                            .addComponent(colorLbl)
                            .addComponent(statusLbl))
                        .addGap(18, 18, 18)
                        .addGroup(carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusCB, 0, 66, Short.MAX_VALUE)
                            .addComponent(colorTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(yearTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(classTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(modelTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(brandTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(plateTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)))
                    .addComponent(clearBtn3)
                    .addComponent(addBtn3))
                .addContainerGap())
        );
        carSearchPanelLayout.setVerticalGroup(
            carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carSearchPanelLayout.createSequentialGroup()
                .addGroup(carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plateLbl)
                    .addComponent(plateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandLbl)
                    .addComponent(brandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelLbl)
                    .addComponent(modelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classLbl)
                    .addComponent(classTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLbl)
                    .addComponent(yearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorLbl)
                    .addComponent(colorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLbl)
                    .addComponent(statusCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(clearBtn3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addBtn3))
        );

        javax.swing.GroupLayout carPanelLayout = new javax.swing.GroupLayout(carPanel);
        carPanel.setLayout(carPanelLayout);
        carPanelLayout.setHorizontalGroup(
            carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(carSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(588, Short.MAX_VALUE))
        );
        carPanelLayout.setVerticalGroup(
            carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(carSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(293, Short.MAX_VALUE))
        );

        tabPanel.addTab(resourceMap.getString("carPanel.TabConstraints.tabTitle"), carPanel); // NOI18N

        carClassPanel.setName("carClassPanel"); // NOI18N

        carClassSearchPanel.setName("carClassSearchPanel"); // NOI18N

        plateLbl1.setText(resourceMap.getString("plateLbl1.text")); // NOI18N
        plateLbl1.setName("plateLbl1"); // NOI18N

        brandLbl1.setText(resourceMap.getString("brandLbl1.text")); // NOI18N
        brandLbl1.setName("brandLbl1"); // NOI18N

        plateTxt1.setName("plateTxt1"); // NOI18N

        brandTxt1.setName("brandTxt1"); // NOI18N

        clearBtn1.setIcon(resourceMap.getIcon("clearBtn1.icon")); // NOI18N
        clearBtn1.setText(resourceMap.getString("clearBtn1.text")); // NOI18N
        clearBtn1.setName("clearBtn1"); // NOI18N

        addBtn1.setAction(actionMap.get("carDialog")); // NOI18N
        addBtn1.setIcon(resourceMap.getIcon("addBtn1.icon")); // NOI18N
        addBtn1.setText(resourceMap.getString("addBtn1.text")); // NOI18N
        addBtn1.setName("addBtn1"); // NOI18N
        addBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout carClassSearchPanelLayout = new javax.swing.GroupLayout(carClassSearchPanel);
        carClassSearchPanel.setLayout(carClassSearchPanelLayout);
        carClassSearchPanelLayout.setHorizontalGroup(
            carClassSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carClassSearchPanelLayout.createSequentialGroup()
                .addGroup(carClassSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(carClassSearchPanelLayout.createSequentialGroup()
                        .addGroup(carClassSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brandLbl1)
                            .addComponent(plateLbl1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(carClassSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plateTxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(brandTxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)))
                    .addComponent(clearBtn1)
                    .addComponent(addBtn1))
                .addContainerGap())
        );
        carClassSearchPanelLayout.setVerticalGroup(
            carClassSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carClassSearchPanelLayout.createSequentialGroup()
                .addGroup(carClassSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plateLbl1)
                    .addComponent(plateTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carClassSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandLbl1)
                    .addComponent(brandTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(clearBtn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addBtn1))
        );

        javax.swing.GroupLayout carClassPanelLayout = new javax.swing.GroupLayout(carClassPanel);
        carClassPanel.setLayout(carClassPanelLayout);
        carClassPanelLayout.setHorizontalGroup(
            carClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carClassPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(carClassSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(564, Short.MAX_VALUE))
        );
        carClassPanelLayout.setVerticalGroup(
            carClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carClassPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(carClassSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(423, Short.MAX_VALUE))
        );

        tabPanel.addTab(resourceMap.getString("carClassPanel.TabConstraints.tabTitle"), carClassPanel); // NOI18N

        logoutBtn.setIcon(resourceMap.getIcon("logout.icon")); // NOI18N
        logoutBtn.setText(resourceMap.getString("logoutBtn.text")); // NOI18N
        logoutBtn.setName("logoutBtn"); // NOI18N

        usernameLbl.setIcon(resourceMap.getIcon("usernameLbl.icon")); // NOI18N
        usernameLbl.setText(resourceMap.getString("usernameLbl.text")); // NOI18N
        usernameLbl.setName("usernameLbl"); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(541, 541, 541)
                .addComponent(usernameLbl)
                .addGap(18, 18, 18)
                .addComponent(logoutBtn))
            .addComponent(tabPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE))
        );

        carDialog.setAlwaysOnTop(true);
        carDialog.setMinimumSize(new java.awt.Dimension(550, 271));
        carDialog.setName("carDialog"); // NOI18N

        saveDlgBtn.setText(resourceMap.getString("saveDlgBtn.text")); // NOI18N
        saveDlgBtn.setName("saveDlgBtn"); // NOI18N

        deleteDlgBtn.setText(resourceMap.getString("deleteDlgBtn.text")); // NOI18N
        deleteDlgBtn.setName("deleteDlgBtn"); // NOI18N

        cancelDlgBtn.setText(resourceMap.getString("cancelDlgBtn.text")); // NOI18N
        cancelDlgBtn.setName("cancelDlgBtn"); // NOI18N

        jPanel4.setName("jPanel4"); // NOI18N

        classCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        classCB.setName("classCB"); // NOI18N

        yearDlgLbl.setText(resourceMap.getString("yearDlgLbl.text")); // NOI18N
        yearDlgLbl.setName("yearDlgLbl"); // NOI18N

        modelDlgTxt.setText(resourceMap.getString("modelDlgTxt.text")); // NOI18N
        modelDlgTxt.setName("modelDlgTxt"); // NOI18N

        classDlgLbl.setText(resourceMap.getString("classDlgLbl.text")); // NOI18N
        classDlgLbl.setName("classDlgLbl"); // NOI18N

        colorDlgTxt.setText(resourceMap.getString("colorDlgTxt.text")); // NOI18N
        colorDlgTxt.setName("colorDlgTxt"); // NOI18N

        yearDlgSpn.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(212), null, null, Integer.valueOf(1)));
        yearDlgSpn.setName("yearDlgSpn"); // NOI18N

        colorDlgLbl.setText(resourceMap.getString("colorDlgLbl.text")); // NOI18N
        colorDlgLbl.setName("colorDlgLbl"); // NOI18N

        statusDlgCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        statusDlgCB.setName("statusDlgCB"); // NOI18N

        statusDlgLbl.setText(resourceMap.getString("statusDlgLbl.text")); // NOI18N
        statusDlgLbl.setName("statusDlgLbl"); // NOI18N

        plateDlgLbl.setText(resourceMap.getString("plateDlgLbl.text")); // NOI18N
        plateDlgLbl.setName("plateDlgLbl"); // NOI18N

        plateDlgTxt.setText(resourceMap.getString("plateDlgTxt.text")); // NOI18N
        plateDlgTxt.setName("plateDlgTxt"); // NOI18N

        brandDlgLbl.setText(resourceMap.getString("brandDlgLbl.text")); // NOI18N
        brandDlgLbl.setName("brandDlgLbl"); // NOI18N

        modelDlgLbl.setText(resourceMap.getString("modelDlgLbl.text")); // NOI18N
        modelDlgLbl.setName("modelDlgLbl"); // NOI18N

        brandDlgTxt.setText(resourceMap.getString("brandDlgTxt.text")); // NOI18N
        brandDlgTxt.setName("brandDlgTxt"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plateDlgLbl)
                    .addComponent(modelDlgLbl)
                    .addComponent(yearDlgLbl)
                    .addComponent(classDlgLbl)
                    .addComponent(colorDlgLbl)
                    .addComponent(statusDlgLbl)
                    .addComponent(brandDlgLbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classCB, javax.swing.GroupLayout.Alignment.TRAILING, 0, 149, Short.MAX_VALUE)
                    .addComponent(modelDlgTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(colorDlgTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(yearDlgSpn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(plateDlgTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(statusDlgCB, javax.swing.GroupLayout.Alignment.TRAILING, 0, 149, Short.MAX_VALUE)
                    .addComponent(brandDlgTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(plateDlgLbl))
                    .addComponent(plateDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandDlgLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(modelDlgLbl))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(modelDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(classDlgLbl))
                    .addComponent(classCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(yearDlgLbl))
                    .addComponent(yearDlgSpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(colorDlgLbl))
                    .addComponent(colorDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(statusDlgLbl))
                    .addComponent(statusDlgCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel5.setName("jPanel5"); // NOI18N

        serviceMonthDlgSpn.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        serviceMonthDlgSpn.setName("serviceMonthDlgSpn"); // NOI18N

        milieageDlgTxt.setText(resourceMap.getString("milieageDlgTxt.text")); // NOI18N
        milieageDlgTxt.setName("milieageDlgTxt"); // NOI18N

        mileageDlgLbl.setText(resourceMap.getString("mileageDlgLbl.text")); // NOI18N
        mileageDlgLbl.setName("mileageDlgLbl"); // NOI18N

        branchCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        branchCB.setName("branchCB"); // NOI18N

        branchDlgLbl.setText(resourceMap.getString("branchDlgLbl.text")); // NOI18N
        branchDlgLbl.setName("branchDlgLbl"); // NOI18N

        lastServiceMileageDlgTxt.setText(resourceMap.getString("lastServiceMileageDlgTxt.text")); // NOI18N
        lastServiceMileageDlgTxt.setName("lastServiceMileageDlgTxt"); // NOI18N

        lastServiceMileageDlgLbl.setText(resourceMap.getString("lastServiceMileageDlgLbl.text")); // NOI18N
        lastServiceMileageDlgLbl.setName("lastServiceMileageDlgLbl"); // NOI18N

        lastServiceDlgLbl.setText(resourceMap.getString("lastServiceDlgLbl.text")); // NOI18N
        lastServiceDlgLbl.setName("lastServiceDlgLbl"); // NOI18N

        serviceMilesDlgLbl.setText(resourceMap.getString("serviceMilesDlgLbl.text")); // NOI18N
        serviceMilesDlgLbl.setName("serviceMilesDlgLbl"); // NOI18N

        serviceMilesDlgTxt.setText(resourceMap.getString("serviceMilesDlgTxt.text")); // NOI18N
        serviceMilesDlgTxt.setName("serviceMilesDlgTxt"); // NOI18N

        serviceMonthDlgLbl.setText(resourceMap.getString("serviceMonthDlgLbl.text")); // NOI18N
        serviceMonthDlgLbl.setName("serviceMonthDlgLbl"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lastServiceDlgLbl)
                    .addComponent(branchDlgLbl)
                    .addComponent(serviceMonthDlgLbl)
                    .addComponent(serviceMilesDlgLbl)
                    .addComponent(lastServiceMileageDlgLbl)
                    .addComponent(mileageDlgLbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(branchCB, 0, 149, Short.MAX_VALUE)
                    .addComponent(serviceMilesDlgTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lastServiceMileageDlgTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(milieageDlgTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                        .addGap(1, 1, 1))
                    .addComponent(serviceMonthDlgSpn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(mileageDlgLbl))
                    .addComponent(milieageDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lastServiceMileageDlgLbl))
                    .addComponent(lastServiceMileageDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE)
                .addComponent(lastServiceDlgLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(branchDlgLbl))
                    .addComponent(branchCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(serviceMonthDlgLbl))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serviceMonthDlgSpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(serviceMilesDlgLbl))
                    .addComponent(serviceMilesDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout carDialogLayout = new javax.swing.GroupLayout(carDialog.getContentPane());
        carDialog.getContentPane().setLayout(carDialogLayout);
        carDialogLayout.setHorizontalGroup(
            carDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carDialogLayout.createSequentialGroup()
                .addGroup(carDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(carDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(carDialogLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(saveDlgBtn)
                        .addGap(18, 18, 18)
                        .addComponent(deleteDlgBtn)
                        .addGap(18, 18, 18)
                        .addComponent(cancelDlgBtn)))
                .addContainerGap())
        );
        carDialogLayout.setVerticalGroup(
            carDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(carDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(carDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(saveDlgBtn)
                    .addComponent(deleteDlgBtn)
                    .addComponent(cancelDlgBtn))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        carClassDialog.setAlwaysOnTop(true);
        carClassDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        carClassDialog.setMinimumSize(new java.awt.Dimension(409, 296));
        carClassDialog.setModal(true);
        carClassDialog.setName("carClassDialog"); // NOI18N

        nameDlgLbl.setText(resourceMap.getString("nameDlgLbl.text")); // NOI18N
        nameDlgLbl.setName("nameDlgLbl"); // NOI18N

        nameDlgTxt.setName("nameDlgTxt"); // NOI18N

        displayNameDlgLbl.setText(resourceMap.getString("displayNameDlgLbl.text")); // NOI18N
        displayNameDlgLbl.setName("displayNameDlgLbl"); // NOI18N

        displayNameDlgTxt.setName("displayNameDlgTxt"); // NOI18N

        priceDlgLbl.setText(resourceMap.getString("priceDlgLbl.text")); // NOI18N
        priceDlgLbl.setName("priceDlgLbl"); // NOI18N

        priceDlgTxt.setName("priceDlgTxt"); // NOI18N

        saveDlgBtn1.setText(resourceMap.getString("saveDlgBtn1.text")); // NOI18N
        saveDlgBtn1.setName("saveDlgBtn1"); // NOI18N

        deleteDlgBtn1.setText(resourceMap.getString("deleteDlgBtn1.text")); // NOI18N
        deleteDlgBtn1.setName("deleteDlgBtn1"); // NOI18N

        cancelDlgBtn1.setText(resourceMap.getString("cancelDlgBtn1.text")); // NOI18N
        cancelDlgBtn1.setName("cancelDlgBtn1"); // NOI18N

        descriptionDlgLbl.setText(resourceMap.getString("descriptionDlgLbl.text")); // NOI18N
        descriptionDlgLbl.setName("descriptionDlgLbl"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout carClassDialogLayout = new javax.swing.GroupLayout(carClassDialog.getContentPane());
        carClassDialog.getContentPane().setLayout(carClassDialogLayout);
        carClassDialogLayout.setHorizontalGroup(
            carClassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carClassDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(carClassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, carClassDialogLayout.createSequentialGroup()
                        .addGroup(carClassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayNameDlgLbl)
                            .addComponent(priceDlgLbl)
                            .addComponent(nameDlgLbl)
                            .addComponent(descriptionDlgLbl))
                        .addGap(18, 18, 18)
                        .addGroup(carClassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addComponent(displayNameDlgTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addComponent(priceDlgTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addGroup(carClassDialogLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(nameDlgTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))))
                    .addGroup(carClassDialogLayout.createSequentialGroup()
                        .addComponent(saveDlgBtn1)
                        .addGap(18, 18, 18)
                        .addComponent(deleteDlgBtn1)
                        .addGap(18, 18, 18)
                        .addComponent(cancelDlgBtn1)))
                .addContainerGap())
        );
        carClassDialogLayout.setVerticalGroup(
            carClassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carClassDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(carClassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameDlgLbl)
                    .addComponent(nameDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(carClassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayNameDlgLbl)
                    .addComponent(displayNameDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(carClassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceDlgLbl)
                    .addComponent(priceDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(carClassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(carClassDialogLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(carClassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(cancelDlgBtn1)
                            .addComponent(deleteDlgBtn1)
                            .addComponent(saveDlgBtn1)))
                    .addComponent(descriptionDlgLbl))
                .addContainerGap())
        );

        staffDialog.setAlwaysOnTop(true);
        staffDialog.setMinimumSize(new java.awt.Dimension(517, 340));
        staffDialog.setModal(true);
        staffDialog.setName("staffDialog"); // NOI18N

        saveDlgBtn2.setText(resourceMap.getString("saveDlgBtn2.text")); // NOI18N
        saveDlgBtn2.setName("saveDlgBtn2"); // NOI18N

        deleteDlgBtn2.setText(resourceMap.getString("deleteDlgBtn2.text")); // NOI18N
        deleteDlgBtn2.setName("deleteDlgBtn2"); // NOI18N

        cancelDlgBtn2.setText(resourceMap.getString("cancelDlgBtn2.text")); // NOI18N
        cancelDlgBtn2.setName("cancelDlgBtn2"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        staffNameDlgLbl.setText(resourceMap.getString("staffNameDlgLbl.text")); // NOI18N
        staffNameDlgLbl.setName("staffNameDlgLbl"); // NOI18N

        surnameDlgLbl.setText(resourceMap.getString("surnameDlgLbl.text")); // NOI18N
        surnameDlgLbl.setName("surnameDlgLbl"); // NOI18N

        usernameDlgLbl.setText(resourceMap.getString("usernameDlgLbl.text")); // NOI18N
        usernameDlgLbl.setName("usernameDlgLbl"); // NOI18N

        passwordDlgLbl.setText(resourceMap.getString("passwordDlgLbl.text")); // NOI18N
        passwordDlgLbl.setName("passwordDlgLbl"); // NOI18N

        passwordPwd.setText(resourceMap.getString("passwordPwd.text")); // NOI18N
        passwordPwd.setName("passwordPwd"); // NOI18N

        usernameDlgTxt.setName("usernameDlgTxt"); // NOI18N

        surnameDlgTxt.setName("surnameDlgTxt"); // NOI18N

        staffNameDlgTxt.setName("staffNameDlgTxt"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordDlgLbl)
                    .addComponent(usernameDlgLbl)
                    .addComponent(surnameDlgLbl)
                    .addComponent(staffNameDlgLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordPwd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(usernameDlgTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(surnameDlgTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(staffNameDlgTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staffNameDlgLbl)
                    .addComponent(staffNameDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surnameDlgLbl)
                    .addComponent(surnameDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameDlgLbl)
                    .addComponent(usernameDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordDlgLbl)
                    .addComponent(passwordPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setName("jPanel3"); // NOI18N

        jScrollPane6.setName("jScrollPane6"); // NOI18N

        addressDlgTA.setColumns(20);
        addressDlgTA.setRows(5);
        addressDlgTA.setName("addressDlgTA"); // NOI18N
        jScrollPane6.setViewportView(addressDlgTA);

        addressDlgLbl.setText(resourceMap.getString("addressDlgLbl.text")); // NOI18N
        addressDlgLbl.setName("addressDlgLbl"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addressDlgLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(addressDlgLbl)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel2.setName("jPanel2"); // NOI18N

        dateOfBirthDlgLbl.setText(resourceMap.getString("dateOfBirthDlgLbl.text")); // NOI18N
        dateOfBirthDlgLbl.setName("dateOfBirthDlgLbl"); // NOI18N

        emailDlgLbl.setText(resourceMap.getString("emailDlgLbl.text")); // NOI18N
        emailDlgLbl.setName("emailDlgLbl"); // NOI18N

        PhoneDlgLbl.setText(resourceMap.getString("PhoneDlgLbl.text")); // NOI18N
        PhoneDlgLbl.setName("PhoneDlgLbl"); // NOI18N

        emailDlgTxt.setName("emailDlgTxt"); // NOI18N

        phoneDlgTxt.setText(resourceMap.getString("phoneDlgTxt.text")); // NOI18N
        phoneDlgTxt.setName("phoneDlgTxt"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateOfBirthDlgLbl)
                    .addComponent(emailDlgLbl)
                    .addComponent(PhoneDlgLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailDlgTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(phoneDlgTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateOfBirthDlgLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailDlgLbl)
                    .addComponent(emailDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneDlgLbl)
                    .addComponent(phoneDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout staffDialogLayout = new javax.swing.GroupLayout(staffDialog.getContentPane());
        staffDialog.getContentPane().setLayout(staffDialogLayout);
        staffDialogLayout.setHorizontalGroup(
            staffDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffDialogLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(staffDialogLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(saveDlgBtn2)
                .addGap(18, 18, 18)
                .addComponent(deleteDlgBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelDlgBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        staffDialogLayout.setVerticalGroup(
            staffDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffDialogLayout.createSequentialGroup()
                .addGroup(staffDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(staffDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteDlgBtn2)
                    .addComponent(cancelDlgBtn2)
                    .addComponent(saveDlgBtn2))
                .addContainerGap())
        );

        setComponent(mainPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void addBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn1ActionPerformed
        carClassDialog.setVisible(true);
    }//GEN-LAST:event_addBtn1ActionPerformed

    private void addBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn3ActionPerformed
        carDialog.setVisible(true);
    }//GEN-LAST:event_addBtn3ActionPerformed

    private void addBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn4ActionPerformed
        staffDialog.setVisible(true);
    }//GEN-LAST:event_addBtn4ActionPerformed

    private void returnDateDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnDateDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnDateDPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PhoneDlgLbl;
    private javax.swing.JButton addBtn1;
    private javax.swing.JButton addBtn2;
    private javax.swing.JButton addBtn3;
    private javax.swing.JButton addBtn4;
    private javax.swing.JLabel addressDlgLbl;
    private javax.swing.JTextArea addressDlgTA;
    private javax.swing.JPanel bookingPanel;
    private javax.swing.JComboBox branchCB;
    private javax.swing.JLabel branchDlgLbl;
    private javax.swing.JLabel brandDlgLbl;
    private javax.swing.JTextField brandDlgTxt;
    private javax.swing.JLabel brandLbl;
    private javax.swing.JLabel brandLbl1;
    private javax.swing.JLabel brandLbl2;
    private javax.swing.JTextField brandTxt;
    private javax.swing.JTextField brandTxt1;
    private javax.swing.JTextField brandTxt2;
    private javax.swing.JButton cancelDlgBtn;
    private javax.swing.JButton cancelDlgBtn1;
    private javax.swing.JButton cancelDlgBtn2;
    private javax.swing.JDialog carClassDialog;
    private javax.swing.JPanel carClassPanel;
    private javax.swing.JPanel carClassSearchPanel;
    private javax.swing.JPanel carClassSearchPanel1;
    private javax.swing.JPanel carClassSearchPanel2;
    private javax.swing.JDialog carDialog;
    private javax.swing.JPanel carPanel;
    private javax.swing.JPanel carSearchPanel;
    private javax.swing.JComboBox classCB;
    private javax.swing.JLabel classDlgLbl;
    private javax.swing.JLabel classLbl;
    private javax.swing.JTextField classTxt;
    private javax.swing.JButton clearBtn1;
    private javax.swing.JButton clearBtn2;
    private javax.swing.JButton clearBtn3;
    private javax.swing.JButton clearBtn4;
    private javax.swing.JLabel colorDlgLbl;
    private javax.swing.JTextField colorDlgTxt;
    private javax.swing.JLabel colorLbl;
    private javax.swing.JTextField colorTxt;
    private javax.swing.JLabel dateOfBirthDlgLbl;
    private javax.swing.JButton deleteDlgBtn;
    private javax.swing.JButton deleteDlgBtn1;
    private javax.swing.JButton deleteDlgBtn2;
    private javax.swing.JLabel descriptionDlgLbl;
    private javax.swing.JLabel displayNameDlgLbl;
    private javax.swing.JTextField displayNameDlgTxt;
    private javax.swing.JLabel emailDlgLbl;
    private javax.swing.JTextField emailDlgTxt;
    private javax.swing.JCheckBox isBookingCB;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lastServiceDlgLbl;
    private javax.swing.JLabel lastServiceMileageDlgLbl;
    private javax.swing.JTextField lastServiceMileageDlgTxt;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel mileageDlgLbl;
    private javax.swing.JTextField milieageDlgTxt;
    private javax.swing.JLabel modelDlgLbl;
    private javax.swing.JTextField modelDlgTxt;
    private javax.swing.JLabel modelLbl;
    private javax.swing.JTextField modelTxt;
    private javax.swing.JLabel nameDlgLbl;
    private javax.swing.JTextField nameDlgTxt;
    private javax.swing.JLabel passwordDlgLbl;
    private javax.swing.JPasswordField passwordPwd;
    private javax.swing.JTextField phoneDlgTxt;
    private javax.swing.JLabel plateDlgLbl;
    private javax.swing.JTextField plateDlgTxt;
    private javax.swing.JLabel plateLbl;
    private javax.swing.JLabel plateLbl1;
    private javax.swing.JLabel plateLbl2;
    private javax.swing.JTextField plateTxt;
    private javax.swing.JTextField plateTxt1;
    private javax.swing.JTextField plateTxt2;
    private javax.swing.JLabel priceDlgLbl;
    private javax.swing.JTextField priceDlgTxt;
    private javax.swing.JLabel refCodeLbl;
    private javax.swing.JTextField refCodeTxt;
    private javax.swing.JLabel rentalDateLbl;
    private javax.swing.JLabel returnDateLbl;
    private javax.swing.JButton saveDlgBtn;
    private javax.swing.JButton saveDlgBtn1;
    private javax.swing.JButton saveDlgBtn2;
    private javax.swing.JLabel serviceMilesDlgLbl;
    private javax.swing.JTextField serviceMilesDlgTxt;
    private javax.swing.JLabel serviceMonthDlgLbl;
    private javax.swing.JSpinner serviceMonthDlgSpn;
    private javax.swing.JDialog staffDialog;
    private javax.swing.JLabel staffNameDlgLbl;
    private javax.swing.JTextField staffNameDlgTxt;
    private javax.swing.JPanel staffPanel;
    private javax.swing.JPanel startPanel;
    private javax.swing.JComboBox statusCB;
    private javax.swing.JComboBox statusDlgCB;
    private javax.swing.JLabel statusDlgLbl;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JLabel surnameDlgLbl;
    private javax.swing.JTextField surnameDlgTxt;
    private javax.swing.JLabel surnameLbl;
    private javax.swing.JTextField surnameTxt;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JLabel usernameDlgLbl;
    private javax.swing.JTextField usernameDlgTxt;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JLabel yearDlgLbl;
    private javax.swing.JSpinner yearDlgSpn;
    private javax.swing.JLabel yearLbl;
    private javax.swing.JTextField yearTxt;
    // End of variables declaration//GEN-END:variables

    public void actionPerformed(ActionEvent e) {
        carDialog.setVisible(true);
    }
}
