/*
 * AdminView.java
 *
 * Created on Apr 2, 2012, 12:32:06 PM
 * @author schiodin
 */
package oscar.view;

import javax.swing.ListSelectionModel;
import oscar.MVC.AbstractView;

/**
 * 
 * @author Draga
 */
public class AdminView extends AbstractView {

    /** Creates new form AdminView */
    public AdminView() {
        initComponents();
        
        staffTbl.setSelectionMode(
                ListSelectionModel.SINGLE_SELECTION);
        rentalTbl.setSelectionMode(
                ListSelectionModel.SINGLE_SELECTION);
        carTbl.setSelectionMode(
                ListSelectionModel.SINGLE_SELECTION);
        carClassTbl.setSelectionMode(
                ListSelectionModel.SINGLE_SELECTION);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carDialog = new javax.swing.JDialog();
        saveDlgBtn = new javax.swing.JButton();
        deleteDlgBtn = new javax.swing.JButton();
        cancelDlgBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        classCB = new javax.swing.JComboBox();
        yearDlgLbl = new javax.swing.JLabel();
        modelDlgTxt = new javax.swing.JTextField();
        classDlgLbl = new javax.swing.JLabel();
        colorDlgTxt = new javax.swing.JTextField();
        yearDlgSpn = new javax.swing.JSpinner();
        colorDlgLbl = new javax.swing.JLabel();
        statusDlgCB = new javax.swing.JComboBox();
        statusDlgLbl = new javax.swing.JLabel();
        plateDlgLbl = new javax.swing.JLabel();
        plateDlgTxt = new javax.swing.JTextField();
        brandDlgLbl = new javax.swing.JLabel();
        modelDlgLbl = new javax.swing.JLabel();
        brandDlgTxt = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        serviceMonthDlgSpn = new javax.swing.JSpinner();
        milieageDlgTxt = new javax.swing.JTextField();
        mileageDlgLbl = new javax.swing.JLabel();
        branchCB = new javax.swing.JComboBox();
        branchDlgLbl = new javax.swing.JLabel();
        lastServiceMileageDlgTxt = new javax.swing.JTextField();
        lastServiceMileageDlgLbl = new javax.swing.JLabel();
        lastServiceDlgLbl = new javax.swing.JLabel();
        serviceMilesDlgLbl = new javax.swing.JLabel();
        serviceMilesDlgTxt = new javax.swing.JTextField();
        serviceMonthDlgLbl = new javax.swing.JLabel();
        carClassDialog = new javax.swing.JDialog();
        nameDlgLbl = new javax.swing.JLabel();
        nameDlgTxt = new javax.swing.JTextField();
        displayNameDlgLbl = new javax.swing.JLabel();
        displayNameDlgTxt = new javax.swing.JTextField();
        priceDlgLbl = new javax.swing.JLabel();
        priceDlgTxt = new javax.swing.JTextField();
        saveDlgBtn1 = new javax.swing.JButton();
        deleteDlgBtn1 = new javax.swing.JButton();
        cancelDlgBtn1 = new javax.swing.JButton();
        descriptionDlgLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        staffDialog = new javax.swing.JDialog();
        saveDlgBtn2 = new javax.swing.JButton();
        deleteDlgBtn2 = new javax.swing.JButton();
        cancelDlgBtn2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        staffNameDlgLbl = new javax.swing.JLabel();
        surnameDlgLbl = new javax.swing.JLabel();
        usernameDlgLbl = new javax.swing.JLabel();
        passwordDlgLbl = new javax.swing.JLabel();
        passwordPwd = new javax.swing.JPasswordField();
        usernameDlgTxt = new javax.swing.JTextField();
        surnameDlgTxt = new javax.swing.JTextField();
        staffNameDlgTxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        addressDlgTA = new javax.swing.JTextArea();
        addressDlgLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        dateOfBirthDlgLbl = new javax.swing.JLabel();
        emailDlgLbl = new javax.swing.JLabel();
        PhoneDlgLbl = new javax.swing.JLabel();
        emailDlgTxt = new javax.swing.JTextField();
        phoneDlgTxt = new javax.swing.JTextField();
        extensionDlg = new javax.swing.JDialog();
        oldDateLbl = new javax.swing.JLabel();
        oldDateDP = new org.jdesktop.swingx.JXDatePicker();
        newDateLbl = new javax.swing.JLabel();
        newDateDP = new org.jdesktop.swingx.JXDatePicker();
        Extendsbtn = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        tabPanel = new javax.swing.JTabbedPane();
        staffPanel = new javax.swing.JPanel();
        carClassSearchPanel1 = new javax.swing.JPanel();
        staffNameLbl = new javax.swing.JLabel();
        staffSurnameLbl = new javax.swing.JLabel();
        staffNameTxt = new javax.swing.JTextField();
        staffSurnameTxt = new javax.swing.JTextField();
        staffAddBtn = new javax.swing.JButton();
        staffClearBtn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        staffTbl = new org.jdesktop.swingx.JXTable();
        rentalPanel = new javax.swing.JPanel();
        rentalSearchPanel = new javax.swing.JPanel();
        refCodeLbl = new javax.swing.JLabel();
        rentalRefCodeTxt = new javax.swing.JTextField();
        surnameLbl = new javax.swing.JLabel();
        rentalSurnameTxt = new javax.swing.JTextField();
        rentalClearBtn = new javax.swing.JButton();
        rentalDeleteBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        rentalTbl = new org.jdesktop.swingx.JXTable();
        carPanel = new javax.swing.JPanel();
        carSearchPanel = new javax.swing.JPanel();
        plateLbl = new javax.swing.JLabel();
        brandLbl = new javax.swing.JLabel();
        modelLbl = new javax.swing.JLabel();
        classLbl = new javax.swing.JLabel();
        yearLbl = new javax.swing.JLabel();
        colorLbl = new javax.swing.JLabel();
        statusLbl = new javax.swing.JLabel();
        carPlateTxt = new javax.swing.JTextField();
        carBrandTxt = new javax.swing.JTextField();
        carModelTxt = new javax.swing.JTextField();
        carClassCb = new javax.swing.JComboBox();
        carYearTxt = new javax.swing.JTextField();
        carColorTxt = new javax.swing.JTextField();
        carStatusCB = new javax.swing.JComboBox();
        carAddBtn = new javax.swing.JButton();
        carClearBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        carTbl = new org.jdesktop.swingx.JXTable();
        carClassPanel = new javax.swing.JPanel();
        carClassSearchPanel = new javax.swing.JPanel();
        carClassNameLbl = new javax.swing.JLabel();
        carClassDisplayLbl = new javax.swing.JLabel();
        carClassNameTxt = new javax.swing.JTextField();
        carClassDisplayTxt = new javax.swing.JTextField();
        carClassClearBtn = new javax.swing.JButton();
        carClassAddBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        carClassTbl = new org.jdesktop.swingx.JXTable();
        openStaffBtn = new javax.swing.JButton();

        carDialog.setAlwaysOnTop(true);
        carDialog.setMinimumSize(new java.awt.Dimension(550, 271));
        carDialog.setName("carDialog"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(AdminView.class);
        saveDlgBtn.setText(resourceMap.getString("saveDlgBtn.text")); // NOI18N
        saveDlgBtn.setName("saveDlgBtn"); // NOI18N

        deleteDlgBtn.setText(resourceMap.getString("deleteDlgBtn.text")); // NOI18N
        deleteDlgBtn.setName("deleteDlgBtn"); // NOI18N

        cancelDlgBtn.setText(resourceMap.getString("cancelDlgBtn.text")); // NOI18N
        cancelDlgBtn.setName("cancelDlgBtn"); // NOI18N

        jPanel4.setName("jPanel4"); // NOI18N

        classCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        classCB.setName("classCB"); // NOI18N

        yearDlgLbl.setText(resourceMap.getString("yearDlgLbl.text")); // NOI18N
        yearDlgLbl.setName("yearDlgLbl"); // NOI18N

        modelDlgTxt.setName("modelDlgTxt"); // NOI18N

        classDlgLbl.setText(resourceMap.getString("classDlgLbl.text")); // NOI18N
        classDlgLbl.setName("classDlgLbl"); // NOI18N

        colorDlgTxt.setName("colorDlgTxt"); // NOI18N

        yearDlgSpn.setName("yearDlgSpn"); // NOI18N

        colorDlgLbl.setText(resourceMap.getString("colorDlgLbl.text")); // NOI18N
        colorDlgLbl.setName("colorDlgLbl"); // NOI18N

        statusDlgCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        statusDlgCB.setName("statusDlgCB"); // NOI18N

        statusDlgLbl.setText(resourceMap.getString("statusDlgLbl.text")); // NOI18N
        statusDlgLbl.setName("statusDlgLbl"); // NOI18N

        plateDlgLbl.setText(resourceMap.getString("plateDlgLbl.text")); // NOI18N
        plateDlgLbl.setName("plateDlgLbl"); // NOI18N

        plateDlgTxt.setName("plateDlgTxt"); // NOI18N

        brandDlgLbl.setText(resourceMap.getString("brandDlgLbl.text")); // NOI18N
        brandDlgLbl.setName("brandDlgLbl"); // NOI18N

        modelDlgLbl.setText(resourceMap.getString("modelDlgLbl.text")); // NOI18N
        modelDlgLbl.setName("modelDlgLbl"); // NOI18N

        brandDlgTxt.setName("brandDlgTxt"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plateDlgLbl)
                    .addComponent(modelDlgLbl)
                    .addComponent(yearDlgLbl)
                    .addComponent(classDlgLbl)
                    .addComponent(colorDlgLbl)
                    .addComponent(statusDlgLbl)
                    .addComponent(brandDlgLbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classCB, javax.swing.GroupLayout.Alignment.TRAILING, 0, 149, Short.MAX_VALUE)
                    .addComponent(modelDlgTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(colorDlgTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(yearDlgSpn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(plateDlgTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(statusDlgCB, javax.swing.GroupLayout.Alignment.TRAILING, 0, 149, Short.MAX_VALUE)
                    .addComponent(brandDlgTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(plateDlgLbl))
                    .addComponent(plateDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandDlgLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(modelDlgLbl))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(modelDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(classDlgLbl))
                    .addComponent(classCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(yearDlgLbl))
                    .addComponent(yearDlgSpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(colorDlgLbl))
                    .addComponent(colorDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(statusDlgLbl))
                    .addComponent(statusDlgCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel5.setName("jPanel5"); // NOI18N

        serviceMonthDlgSpn.setName("serviceMonthDlgSpn"); // NOI18N

        milieageDlgTxt.setName("milieageDlgTxt"); // NOI18N

        mileageDlgLbl.setText(resourceMap.getString("mileageDlgLbl.text")); // NOI18N
        mileageDlgLbl.setName("mileageDlgLbl"); // NOI18N

        branchCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        branchCB.setName("branchCB"); // NOI18N

        branchDlgLbl.setText(resourceMap.getString("branchDlgLbl.text")); // NOI18N
        branchDlgLbl.setName("branchDlgLbl"); // NOI18N

        lastServiceMileageDlgTxt.setName("lastServiceMileageDlgTxt"); // NOI18N

        lastServiceMileageDlgLbl.setText(resourceMap.getString("lastServiceMileageDlgLbl.text")); // NOI18N
        lastServiceMileageDlgLbl.setName("lastServiceMileageDlgLbl"); // NOI18N

        lastServiceDlgLbl.setText(resourceMap.getString("lastServiceDlgLbl.text")); // NOI18N
        lastServiceDlgLbl.setName("lastServiceDlgLbl"); // NOI18N

        serviceMilesDlgLbl.setText(resourceMap.getString("serviceMilesDlgLbl.text")); // NOI18N
        serviceMilesDlgLbl.setName("serviceMilesDlgLbl"); // NOI18N

        serviceMilesDlgTxt.setName("serviceMilesDlgTxt"); // NOI18N

        serviceMonthDlgLbl.setText(resourceMap.getString("serviceMonthDlgLbl.text")); // NOI18N
        serviceMonthDlgLbl.setName("serviceMonthDlgLbl"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lastServiceDlgLbl)
                    .addComponent(branchDlgLbl)
                    .addComponent(serviceMonthDlgLbl)
                    .addComponent(serviceMilesDlgLbl)
                    .addComponent(lastServiceMileageDlgLbl)
                    .addComponent(mileageDlgLbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(branchCB, 0, 149, Short.MAX_VALUE)
                    .addComponent(serviceMilesDlgTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lastServiceMileageDlgTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(milieageDlgTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                        .addGap(1, 1, 1))
                    .addComponent(serviceMonthDlgSpn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(mileageDlgLbl))
                    .addComponent(milieageDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lastServiceMileageDlgLbl))
                    .addComponent(lastServiceMileageDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastServiceDlgLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(branchDlgLbl))
                    .addComponent(branchCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(serviceMonthDlgLbl))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serviceMonthDlgSpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(serviceMilesDlgLbl))
                    .addComponent(serviceMilesDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout carDialogLayout = new javax.swing.GroupLayout(carDialog.getContentPane());
        carDialog.getContentPane().setLayout(carDialogLayout);
        carDialogLayout.setHorizontalGroup(
            carDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carDialogLayout.createSequentialGroup()
                .addGroup(carDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(carDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(carDialogLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(saveDlgBtn)
                        .addGap(18, 18, 18)
                        .addComponent(deleteDlgBtn)
                        .addGap(18, 18, 18)
                        .addComponent(cancelDlgBtn)))
                .addContainerGap())
        );
        carDialogLayout.setVerticalGroup(
            carDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(carDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(carDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(saveDlgBtn)
                    .addComponent(deleteDlgBtn)
                    .addComponent(cancelDlgBtn))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        carClassDialog.setAlwaysOnTop(true);
        carClassDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        carClassDialog.setMinimumSize(new java.awt.Dimension(409, 296));
        carClassDialog.setModal(true);
        carClassDialog.setName("carClassDialog"); // NOI18N

        nameDlgLbl.setText(resourceMap.getString("nameDlgLbl.text")); // NOI18N
        nameDlgLbl.setName("nameDlgLbl"); // NOI18N

        nameDlgTxt.setName("nameDlgTxt"); // NOI18N

        displayNameDlgLbl.setText(resourceMap.getString("displayNameDlgLbl.text")); // NOI18N
        displayNameDlgLbl.setName("displayNameDlgLbl"); // NOI18N

        displayNameDlgTxt.setName("displayNameDlgTxt"); // NOI18N

        priceDlgLbl.setText(resourceMap.getString("priceDlgLbl.text")); // NOI18N
        priceDlgLbl.setName("priceDlgLbl"); // NOI18N

        priceDlgTxt.setName("priceDlgTxt"); // NOI18N

        saveDlgBtn1.setText(resourceMap.getString("saveDlgBtn1.text")); // NOI18N
        saveDlgBtn1.setName("saveDlgBtn1"); // NOI18N

        deleteDlgBtn1.setText(resourceMap.getString("deleteDlgBtn1.text")); // NOI18N
        deleteDlgBtn1.setName("deleteDlgBtn1"); // NOI18N

        cancelDlgBtn1.setText(resourceMap.getString("cancelDlgBtn1.text")); // NOI18N
        cancelDlgBtn1.setName("cancelDlgBtn1"); // NOI18N

        descriptionDlgLbl.setText(resourceMap.getString("descriptionDlgLbl.text")); // NOI18N
        descriptionDlgLbl.setName("descriptionDlgLbl"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout carClassDialogLayout = new javax.swing.GroupLayout(carClassDialog.getContentPane());
        carClassDialog.getContentPane().setLayout(carClassDialogLayout);
        carClassDialogLayout.setHorizontalGroup(
            carClassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carClassDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(carClassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, carClassDialogLayout.createSequentialGroup()
                        .addGroup(carClassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayNameDlgLbl)
                            .addComponent(priceDlgLbl)
                            .addComponent(nameDlgLbl)
                            .addComponent(descriptionDlgLbl))
                        .addGap(18, 18, 18)
                        .addGroup(carClassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addComponent(displayNameDlgTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addComponent(priceDlgTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addGroup(carClassDialogLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(nameDlgTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))))
                    .addGroup(carClassDialogLayout.createSequentialGroup()
                        .addComponent(saveDlgBtn1)
                        .addGap(18, 18, 18)
                        .addComponent(deleteDlgBtn1)
                        .addGap(18, 18, 18)
                        .addComponent(cancelDlgBtn1)))
                .addContainerGap())
        );
        carClassDialogLayout.setVerticalGroup(
            carClassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carClassDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(carClassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameDlgLbl)
                    .addComponent(nameDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(carClassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayNameDlgLbl)
                    .addComponent(displayNameDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(carClassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceDlgLbl)
                    .addComponent(priceDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(carClassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(carClassDialogLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(carClassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(cancelDlgBtn1)
                            .addComponent(deleteDlgBtn1)
                            .addComponent(saveDlgBtn1)))
                    .addComponent(descriptionDlgLbl))
                .addContainerGap())
        );

        staffDialog.setAlwaysOnTop(true);
        staffDialog.setMinimumSize(new java.awt.Dimension(517, 340));
        staffDialog.setModal(true);
        staffDialog.setName("staffDialog"); // NOI18N

        saveDlgBtn2.setIcon(resourceMap.getIcon("saveDlgBtn2.icon")); // NOI18N
        saveDlgBtn2.setText(resourceMap.getString("saveDlgBtn2.text")); // NOI18N
        saveDlgBtn2.setName("saveDlgBtn2"); // NOI18N

        deleteDlgBtn2.setIcon(resourceMap.getIcon("deleteDlgBtn2.icon")); // NOI18N
        deleteDlgBtn2.setText(resourceMap.getString("deleteDlgBtn2.text")); // NOI18N
        deleteDlgBtn2.setName("deleteDlgBtn2"); // NOI18N

        cancelDlgBtn2.setIcon(resourceMap.getIcon("cancelDlgBtn2.icon")); // NOI18N
        cancelDlgBtn2.setText(resourceMap.getString("cancelDlgBtn2.text")); // NOI18N
        cancelDlgBtn2.setName("cancelDlgBtn2"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        staffNameDlgLbl.setText(resourceMap.getString("staffNameDlgLbl.text")); // NOI18N
        staffNameDlgLbl.setName("staffNameDlgLbl"); // NOI18N

        surnameDlgLbl.setText(resourceMap.getString("surnameDlgLbl.text")); // NOI18N
        surnameDlgLbl.setName("surnameDlgLbl"); // NOI18N

        usernameDlgLbl.setText(resourceMap.getString("usernameDlgLbl.text")); // NOI18N
        usernameDlgLbl.setName("usernameDlgLbl"); // NOI18N

        passwordDlgLbl.setText(resourceMap.getString("passwordDlgLbl.text")); // NOI18N
        passwordDlgLbl.setName("passwordDlgLbl"); // NOI18N

        passwordPwd.setName("passwordPwd"); // NOI18N

        usernameDlgTxt.setName("usernameDlgTxt"); // NOI18N

        surnameDlgTxt.setName("surnameDlgTxt"); // NOI18N

        staffNameDlgTxt.setName("staffNameDlgTxt"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordDlgLbl)
                    .addComponent(usernameDlgLbl)
                    .addComponent(surnameDlgLbl)
                    .addComponent(staffNameDlgLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordPwd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(usernameDlgTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(surnameDlgTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(staffNameDlgTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staffNameDlgLbl)
                    .addComponent(staffNameDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surnameDlgLbl)
                    .addComponent(surnameDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameDlgLbl)
                    .addComponent(usernameDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordDlgLbl)
                    .addComponent(passwordPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setName("jPanel3"); // NOI18N

        jScrollPane6.setName("jScrollPane6"); // NOI18N

        addressDlgTA.setColumns(20);
        addressDlgTA.setRows(5);
        addressDlgTA.setName("addressDlgTA"); // NOI18N
        jScrollPane6.setViewportView(addressDlgTA);

        addressDlgLbl.setText(resourceMap.getString("addressDlgLbl.text")); // NOI18N
        addressDlgLbl.setName("addressDlgLbl"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addressDlgLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(addressDlgLbl)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel2.setName("jPanel2"); // NOI18N

        dateOfBirthDlgLbl.setText(resourceMap.getString("dateOfBirthDlgLbl.text")); // NOI18N
        dateOfBirthDlgLbl.setName("dateOfBirthDlgLbl"); // NOI18N

        emailDlgLbl.setText(resourceMap.getString("emailDlgLbl.text")); // NOI18N
        emailDlgLbl.setName("emailDlgLbl"); // NOI18N

        PhoneDlgLbl.setText(resourceMap.getString("PhoneDlgLbl.text")); // NOI18N
        PhoneDlgLbl.setName("PhoneDlgLbl"); // NOI18N

        emailDlgTxt.setName("emailDlgTxt"); // NOI18N

        phoneDlgTxt.setName("phoneDlgTxt"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateOfBirthDlgLbl)
                    .addComponent(emailDlgLbl)
                    .addComponent(PhoneDlgLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailDlgTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(phoneDlgTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateOfBirthDlgLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailDlgLbl)
                    .addComponent(emailDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneDlgLbl)
                    .addComponent(phoneDlgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout staffDialogLayout = new javax.swing.GroupLayout(staffDialog.getContentPane());
        staffDialog.getContentPane().setLayout(staffDialogLayout);
        staffDialogLayout.setHorizontalGroup(
            staffDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffDialogLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(staffDialogLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(saveDlgBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(deleteDlgBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(cancelDlgBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(108, 108, 108))
        );
        staffDialogLayout.setVerticalGroup(
            staffDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffDialogLayout.createSequentialGroup()
                .addGroup(staffDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(staffDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteDlgBtn2)
                    .addComponent(cancelDlgBtn2)
                    .addComponent(saveDlgBtn2))
                .addContainerGap())
        );

        extensionDlg.setTitle(resourceMap.getString("extensionDlg.title")); // NOI18N
        extensionDlg.setAlwaysOnTop(true);
        extensionDlg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        extensionDlg.setIconImage(null);
        extensionDlg.setMinimumSize(new java.awt.Dimension(281, 200));
        extensionDlg.setModal(true);
        extensionDlg.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        extensionDlg.setName("extensionDlg"); // NOI18N
        extensionDlg.setResizable(false);

        oldDateLbl.setText(resourceMap.getString("oldDateLbl.text")); // NOI18N
        oldDateLbl.setName("oldDateLbl"); // NOI18N

        oldDateDP.setEditable(false);
        oldDateDP.setName("oldDateDP"); // NOI18N

        newDateLbl.setText(resourceMap.getString("newDateLbl.text")); // NOI18N
        newDateLbl.setName("newDateLbl"); // NOI18N

        newDateDP.setName("newDateDP"); // NOI18N

        Extendsbtn.setText(resourceMap.getString("Extendsbtn.text")); // NOI18N
        Extendsbtn.setName("Extendsbtn"); // NOI18N

        javax.swing.GroupLayout extensionDlgLayout = new javax.swing.GroupLayout(extensionDlg.getContentPane());
        extensionDlg.getContentPane().setLayout(extensionDlgLayout);
        extensionDlgLayout.setHorizontalGroup(
            extensionDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(extensionDlgLayout.createSequentialGroup()
                .addGroup(extensionDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, extensionDlgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(extensionDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oldDateLbl)
                            .addComponent(newDateLbl))
                        .addGap(23, 23, 23)
                        .addGroup(extensionDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newDateDP, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oldDateDP, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                    .addGroup(extensionDlgLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(Extendsbtn)))
                .addContainerGap())
        );
        extensionDlgLayout.setVerticalGroup(
            extensionDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(extensionDlgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(extensionDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldDateLbl)
                    .addComponent(oldDateDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(extensionDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newDateLbl)
                    .addComponent(newDateDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Extendsbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Admin"); // NOI18N

        mainPanel.setName("mainPanel"); // NOI18N

        tabPanel.setName("tabPanel"); // NOI18N

        staffPanel.setName("staffPanel"); // NOI18N

        carClassSearchPanel1.setName("carClassSearchPanel1"); // NOI18N

        staffNameLbl.setText(resourceMap.getString("staffNameLbl.text")); // NOI18N
        staffNameLbl.setName("staffNameLbl"); // NOI18N

        staffSurnameLbl.setText(resourceMap.getString("staffSurnameLbl.text")); // NOI18N
        staffSurnameLbl.setName("staffSurnameLbl"); // NOI18N

        staffNameTxt.setName("staffNameTxt"); // NOI18N

        staffSurnameTxt.setName("staffSurnameTxt"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(AdminView.class, this);
        staffAddBtn.setAction(actionMap.get("carDialog")); // NOI18N
        staffAddBtn.setIcon(resourceMap.getIcon("staffAddBtn.icon")); // NOI18N
        staffAddBtn.setText(resourceMap.getString("staffAddBtn.text")); // NOI18N
        staffAddBtn.setName("staffAddBtn"); // NOI18N

        staffClearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oscar/view/resources/clean.png"))); // NOI18N
        staffClearBtn.setText(resourceMap.getString("staffClearBtn.text")); // NOI18N
        staffClearBtn.setName("staffClearBtn"); // NOI18N

        javax.swing.GroupLayout carClassSearchPanel1Layout = new javax.swing.GroupLayout(carClassSearchPanel1);
        carClassSearchPanel1.setLayout(carClassSearchPanel1Layout);
        carClassSearchPanel1Layout.setHorizontalGroup(
            carClassSearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carClassSearchPanel1Layout.createSequentialGroup()
                .addGroup(carClassSearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(staffClearBtn)
                    .addComponent(staffAddBtn)
                    .addGroup(carClassSearchPanel1Layout.createSequentialGroup()
                        .addGroup(carClassSearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(staffSurnameLbl)
                            .addComponent(staffNameLbl))
                        .addGap(18, 18, 18)
                        .addGroup(carClassSearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(staffSurnameTxt)
                            .addComponent(staffNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                        .addGap(42, 42, 42)))
                .addContainerGap())
        );
        carClassSearchPanel1Layout.setVerticalGroup(
            carClassSearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carClassSearchPanel1Layout.createSequentialGroup()
                .addGroup(carClassSearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staffNameLbl)
                    .addComponent(staffNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carClassSearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(staffSurnameLbl)
                    .addComponent(staffSurnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(staffClearBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staffAddBtn))
        );

        jScrollPane5.setName("jScrollPane5"); // NOI18N

        staffTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        staffTbl.setAutoStartEditOnKeyStroke(false);
        staffTbl.setEditable(false);
        staffTbl.setName("staffTbl"); // NOI18N
        staffTbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(staffTbl);
        staffTbl.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout staffPanelLayout = new javax.swing.GroupLayout(staffPanel);
        staffPanel.setLayout(staffPanelLayout);
        staffPanelLayout.setHorizontalGroup(
            staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(carClassSearchPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addContainerGap())
        );
        staffPanelLayout.setVerticalGroup(
            staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                    .addComponent(carClassSearchPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabPanel.addTab(resourceMap.getString("staffPanel.TabConstraints.tabTitle"), staffPanel); // NOI18N

        rentalPanel.setName("rentalPanel"); // NOI18N

        rentalSearchPanel.setName("rentalSearchPanel"); // NOI18N

        refCodeLbl.setText(resourceMap.getString("refCodeLbl.text")); // NOI18N
        refCodeLbl.setName("refCodeLbl"); // NOI18N

        rentalRefCodeTxt.setName("rentalRefCodeTxt"); // NOI18N

        surnameLbl.setText(resourceMap.getString("surnameLbl.text")); // NOI18N
        surnameLbl.setName("surnameLbl"); // NOI18N

        rentalSurnameTxt.setName("rentalSurnameTxt"); // NOI18N

        rentalClearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oscar/view/resources/clean.png"))); // NOI18N
        rentalClearBtn.setText(resourceMap.getString("rentalClearBtn.text")); // NOI18N
        rentalClearBtn.setName("rentalClearBtn"); // NOI18N

        rentalDeleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oscar/view/resources/delete.png"))); // NOI18N
        rentalDeleteBtn.setText(resourceMap.getString("rentalDeleteBtn.text")); // NOI18N
        rentalDeleteBtn.setName("rentalDeleteBtn"); // NOI18N

        javax.swing.GroupLayout rentalSearchPanelLayout = new javax.swing.GroupLayout(rentalSearchPanel);
        rentalSearchPanel.setLayout(rentalSearchPanelLayout);
        rentalSearchPanelLayout.setHorizontalGroup(
            rentalSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentalSearchPanelLayout.createSequentialGroup()
                .addGroup(rentalSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rentalSearchPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(rentalSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(refCodeLbl)
                            .addComponent(surnameLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(rentalSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rentalRefCodeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(rentalSurnameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)))
                    .addComponent(rentalClearBtn)
                    .addComponent(rentalDeleteBtn))
                .addContainerGap())
        );
        rentalSearchPanelLayout.setVerticalGroup(
            rentalSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentalSearchPanelLayout.createSequentialGroup()
                .addGroup(rentalSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentalRefCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refCodeLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rentalSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentalSurnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surnameLbl))
                .addGap(18, 18, 18)
                .addComponent(rentalClearBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rentalDeleteBtn))
        );

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        rentalTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        rentalTbl.setAutoStartEditOnKeyStroke(false);
        rentalTbl.setEditable(false);
        rentalTbl.setName("rentalTbl"); // NOI18N
        rentalTbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(rentalTbl);
        rentalTbl.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout rentalPanelLayout = new javax.swing.GroupLayout(rentalPanel);
        rentalPanel.setLayout(rentalPanelLayout);
        rentalPanelLayout.setHorizontalGroup(
            rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rentalSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                .addContainerGap())
        );
        rentalPanelLayout.setVerticalGroup(
            rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rentalSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabPanel.addTab(resourceMap.getString("rentalPanel.TabConstraints.tabTitle"), rentalPanel); // NOI18N

        carPanel.setName("carPanel"); // NOI18N

        carSearchPanel.setName("carSearchPanel"); // NOI18N

        plateLbl.setText(resourceMap.getString("plateLbl.text")); // NOI18N
        plateLbl.setName("plateLbl"); // NOI18N

        brandLbl.setText(resourceMap.getString("brandLbl.text")); // NOI18N
        brandLbl.setName("brandLbl"); // NOI18N

        modelLbl.setText(resourceMap.getString("modelLbl.text")); // NOI18N
        modelLbl.setName("modelLbl"); // NOI18N

        classLbl.setText(resourceMap.getString("classLbl.text")); // NOI18N
        classLbl.setName("classLbl"); // NOI18N

        yearLbl.setText(resourceMap.getString("yearLbl.text")); // NOI18N
        yearLbl.setName("yearLbl"); // NOI18N

        colorLbl.setText(resourceMap.getString("colorLbl.text")); // NOI18N
        colorLbl.setName("colorLbl"); // NOI18N

        statusLbl.setText(resourceMap.getString("statusLbl.text")); // NOI18N
        statusLbl.setEnabled(false);
        statusLbl.setName("statusLbl"); // NOI18N

        carPlateTxt.setName("carPlateTxt"); // NOI18N

        carBrandTxt.setName("carBrandTxt"); // NOI18N

        carModelTxt.setName("carModelTxt"); // NOI18N

        carClassCb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        carClassCb.setName("carClassCb"); // NOI18N

        carYearTxt.setName("carYearTxt"); // NOI18N

        carColorTxt.setName("carColorTxt"); // NOI18N

        carStatusCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        carStatusCB.setEnabled(false);
        carStatusCB.setName("carStatusCB"); // NOI18N

        carAddBtn.setAction(actionMap.get("carDialog")); // NOI18N
        carAddBtn.setIcon(resourceMap.getIcon("carAddBtn.icon")); // NOI18N
        carAddBtn.setText(resourceMap.getString("carAddBtn.text")); // NOI18N
        carAddBtn.setName("carAddBtn"); // NOI18N

        carClearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oscar/view/resources/clean.png"))); // NOI18N
        carClearBtn.setText(resourceMap.getString("carClearBtn.text")); // NOI18N
        carClearBtn.setName("carClearBtn"); // NOI18N

        javax.swing.GroupLayout carSearchPanelLayout = new javax.swing.GroupLayout(carSearchPanel);
        carSearchPanel.setLayout(carSearchPanelLayout);
        carSearchPanelLayout.setHorizontalGroup(
            carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carSearchPanelLayout.createSequentialGroup()
                .addGroup(carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(carSearchPanelLayout.createSequentialGroup()
                        .addGroup(carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brandLbl)
                            .addComponent(plateLbl)
                            .addComponent(modelLbl)
                            .addComponent(classLbl)
                            .addComponent(yearLbl)
                            .addComponent(colorLbl)
                            .addComponent(statusLbl))
                        .addGap(18, 18, 18)
                        .addGroup(carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(carStatusCB, javax.swing.GroupLayout.Alignment.LEADING, 0, 66, Short.MAX_VALUE)
                            .addComponent(carColorTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(carYearTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(carModelTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(carBrandTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(carPlateTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(carClassCb, 0, 66, Short.MAX_VALUE)))
                    .addComponent(carClearBtn)
                    .addComponent(carAddBtn))
                .addContainerGap())
        );
        carSearchPanelLayout.setVerticalGroup(
            carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carSearchPanelLayout.createSequentialGroup()
                .addGroup(carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plateLbl)
                    .addComponent(carPlateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandLbl)
                    .addComponent(carBrandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelLbl)
                    .addComponent(carModelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classLbl)
                    .addComponent(carClassCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLbl)
                    .addComponent(carYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorLbl)
                    .addComponent(carColorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLbl)
                    .addComponent(carStatusCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(carClearBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carAddBtn))
        );

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        carTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        carTbl.setAutoStartEditOnKeyStroke(false);
        carTbl.setEditable(false);
        carTbl.setName("carTbl"); // NOI18N
        carTbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(carTbl);
        carTbl.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout carPanelLayout = new javax.swing.GroupLayout(carPanel);
        carPanel.setLayout(carPanelLayout);
        carPanelLayout.setHorizontalGroup(
            carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(carSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                .addContainerGap())
        );
        carPanelLayout.setVerticalGroup(
            carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                    .addComponent(carSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabPanel.addTab(resourceMap.getString("carPanel.TabConstraints.tabTitle"), carPanel); // NOI18N

        carClassPanel.setName("carClassPanel"); // NOI18N

        carClassSearchPanel.setName("carClassSearchPanel"); // NOI18N

        carClassNameLbl.setText(resourceMap.getString("carClassNameLbl.text")); // NOI18N
        carClassNameLbl.setName("carClassNameLbl"); // NOI18N

        carClassDisplayLbl.setText(resourceMap.getString("carClassDisplayLbl.text")); // NOI18N
        carClassDisplayLbl.setName("carClassDisplayLbl"); // NOI18N

        carClassNameTxt.setName("carClassNameTxt"); // NOI18N

        carClassDisplayTxt.setName("carClassDisplayTxt"); // NOI18N

        carClassClearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oscar/view/resources/clean.png"))); // NOI18N
        carClassClearBtn.setText(resourceMap.getString("carClassClearBtn.text")); // NOI18N
        carClassClearBtn.setName("carClassClearBtn"); // NOI18N

        carClassAddBtn.setAction(actionMap.get("carDialog")); // NOI18N
        carClassAddBtn.setIcon(resourceMap.getIcon("carClassAddBtn.icon")); // NOI18N
        carClassAddBtn.setText(resourceMap.getString("carClassAddBtn.text")); // NOI18N
        carClassAddBtn.setName("carClassAddBtn"); // NOI18N

        javax.swing.GroupLayout carClassSearchPanelLayout = new javax.swing.GroupLayout(carClassSearchPanel);
        carClassSearchPanel.setLayout(carClassSearchPanelLayout);
        carClassSearchPanelLayout.setHorizontalGroup(
            carClassSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carClassSearchPanelLayout.createSequentialGroup()
                .addGroup(carClassSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(carClassSearchPanelLayout.createSequentialGroup()
                        .addGroup(carClassSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(carClassDisplayLbl)
                            .addComponent(carClassNameLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(carClassSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(carClassNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(carClassDisplayTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)))
                    .addComponent(carClassClearBtn)
                    .addComponent(carClassAddBtn))
                .addContainerGap())
        );
        carClassSearchPanelLayout.setVerticalGroup(
            carClassSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carClassSearchPanelLayout.createSequentialGroup()
                .addGroup(carClassSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carClassNameLbl)
                    .addComponent(carClassNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carClassSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carClassDisplayLbl)
                    .addComponent(carClassDisplayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(carClassClearBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carClassAddBtn))
        );

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        carClassTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        carClassTbl.setAutoStartEditOnKeyStroke(false);
        carClassTbl.setEditable(false);
        carClassTbl.setName("carClassTbl"); // NOI18N
        carClassTbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(carClassTbl);
        carClassTbl.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout carClassPanelLayout = new javax.swing.GroupLayout(carClassPanel);
        carClassPanel.setLayout(carClassPanelLayout);
        carClassPanelLayout.setHorizontalGroup(
            carClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carClassPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(carClassSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addContainerGap())
        );
        carClassPanelLayout.setVerticalGroup(
            carClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carClassPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(carClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                    .addComponent(carClassSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabPanel.addTab(resourceMap.getString("carClassPanel.TabConstraints.tabTitle"), carClassPanel); // NOI18N

        openStaffBtn.setIcon(resourceMap.getIcon("openStaffBtn.icon")); // NOI18N
        openStaffBtn.setText(resourceMap.getString("openStaffBtn.text")); // NOI18N
        openStaffBtn.setName("openStaffBtn"); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                    .addComponent(openStaffBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(openStaffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new AdminView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Extendsbtn;
    private javax.swing.JLabel PhoneDlgLbl;
    private javax.swing.JLabel addressDlgLbl;
    private javax.swing.JTextArea addressDlgTA;
    private javax.swing.JComboBox branchCB;
    private javax.swing.JLabel branchDlgLbl;
    private javax.swing.JLabel brandDlgLbl;
    private javax.swing.JTextField brandDlgTxt;
    private javax.swing.JLabel brandLbl;
    private javax.swing.JButton cancelDlgBtn;
    private javax.swing.JButton cancelDlgBtn1;
    private javax.swing.JButton cancelDlgBtn2;
    private javax.swing.JButton carAddBtn;
    private javax.swing.JTextField carBrandTxt;
    private javax.swing.JButton carClassAddBtn;
    private javax.swing.JComboBox carClassCb;
    private javax.swing.JButton carClassClearBtn;
    private javax.swing.JDialog carClassDialog;
    private javax.swing.JLabel carClassDisplayLbl;
    private javax.swing.JTextField carClassDisplayTxt;
    private javax.swing.JLabel carClassNameLbl;
    private javax.swing.JTextField carClassNameTxt;
    private javax.swing.JPanel carClassPanel;
    private javax.swing.JPanel carClassSearchPanel;
    private javax.swing.JPanel carClassSearchPanel1;
    private org.jdesktop.swingx.JXTable carClassTbl;
    private javax.swing.JButton carClearBtn;
    private javax.swing.JTextField carColorTxt;
    private javax.swing.JDialog carDialog;
    private javax.swing.JTextField carModelTxt;
    private javax.swing.JPanel carPanel;
    private javax.swing.JTextField carPlateTxt;
    private javax.swing.JPanel carSearchPanel;
    private javax.swing.JComboBox carStatusCB;
    private org.jdesktop.swingx.JXTable carTbl;
    private javax.swing.JTextField carYearTxt;
    private javax.swing.JComboBox classCB;
    private javax.swing.JLabel classDlgLbl;
    private javax.swing.JLabel classLbl;
    private javax.swing.JLabel colorDlgLbl;
    private javax.swing.JTextField colorDlgTxt;
    private javax.swing.JLabel colorLbl;
    private javax.swing.JLabel dateOfBirthDlgLbl;
    private javax.swing.JButton deleteDlgBtn;
    private javax.swing.JButton deleteDlgBtn1;
    private javax.swing.JButton deleteDlgBtn2;
    private javax.swing.JLabel descriptionDlgLbl;
    private javax.swing.JLabel displayNameDlgLbl;
    private javax.swing.JTextField displayNameDlgTxt;
    private javax.swing.JLabel emailDlgLbl;
    private javax.swing.JTextField emailDlgTxt;
    private javax.swing.JDialog extensionDlg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lastServiceDlgLbl;
    private javax.swing.JLabel lastServiceMileageDlgLbl;
    private javax.swing.JTextField lastServiceMileageDlgTxt;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel mileageDlgLbl;
    private javax.swing.JTextField milieageDlgTxt;
    private javax.swing.JLabel modelDlgLbl;
    private javax.swing.JTextField modelDlgTxt;
    private javax.swing.JLabel modelLbl;
    private javax.swing.JLabel nameDlgLbl;
    private javax.swing.JTextField nameDlgTxt;
    private org.jdesktop.swingx.JXDatePicker newDateDP;
    private javax.swing.JLabel newDateLbl;
    private org.jdesktop.swingx.JXDatePicker oldDateDP;
    private javax.swing.JLabel oldDateLbl;
    private javax.swing.JButton openStaffBtn;
    private javax.swing.JLabel passwordDlgLbl;
    private javax.swing.JPasswordField passwordPwd;
    private javax.swing.JTextField phoneDlgTxt;
    private javax.swing.JLabel plateDlgLbl;
    private javax.swing.JTextField plateDlgTxt;
    private javax.swing.JLabel plateLbl;
    private javax.swing.JLabel priceDlgLbl;
    private javax.swing.JTextField priceDlgTxt;
    private javax.swing.JLabel refCodeLbl;
    private javax.swing.JButton rentalClearBtn;
    private javax.swing.JButton rentalDeleteBtn;
    private javax.swing.JPanel rentalPanel;
    private javax.swing.JTextField rentalRefCodeTxt;
    private javax.swing.JPanel rentalSearchPanel;
    private javax.swing.JTextField rentalSurnameTxt;
    private org.jdesktop.swingx.JXTable rentalTbl;
    private javax.swing.JButton saveDlgBtn;
    private javax.swing.JButton saveDlgBtn1;
    private javax.swing.JButton saveDlgBtn2;
    private javax.swing.JLabel serviceMilesDlgLbl;
    private javax.swing.JTextField serviceMilesDlgTxt;
    private javax.swing.JLabel serviceMonthDlgLbl;
    private javax.swing.JSpinner serviceMonthDlgSpn;
    private javax.swing.JButton staffAddBtn;
    private javax.swing.JButton staffClearBtn;
    private javax.swing.JDialog staffDialog;
    private javax.swing.JLabel staffNameDlgLbl;
    private javax.swing.JTextField staffNameDlgTxt;
    private javax.swing.JLabel staffNameLbl;
    private javax.swing.JTextField staffNameTxt;
    private javax.swing.JPanel staffPanel;
    private javax.swing.JLabel staffSurnameLbl;
    private javax.swing.JTextField staffSurnameTxt;
    private org.jdesktop.swingx.JXTable staffTbl;
    private javax.swing.JComboBox statusDlgCB;
    private javax.swing.JLabel statusDlgLbl;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JLabel surnameDlgLbl;
    private javax.swing.JTextField surnameDlgTxt;
    private javax.swing.JLabel surnameLbl;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JLabel usernameDlgLbl;
    private javax.swing.JTextField usernameDlgTxt;
    private javax.swing.JLabel yearDlgLbl;
    private javax.swing.JSpinner yearDlgSpn;
    private javax.swing.JLabel yearLbl;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getOpenStaffBtn() {
        return openStaffBtn;
    }
    
    public org.jdesktop.swingx.JXTable getStaffTbl() {
        return staffTbl;
    }
    
    public javax.swing.JButton getStaffAddBtn() {
        return staffAddBtn;
    }
    
    public javax.swing.JButton getStaffClearBtn() {
        return staffClearBtn;
    }
    
    public javax.swing.JTextField getStaffNameTxt() {
        return staffNameTxt;
    }
    
    public javax.swing.JTextField getStaffSurnameTxt() {
        return staffSurnameTxt;
    }
    
    public javax.swing.JDialog getCarClassDialog() {
        return carClassDialog;
    }
    
    public javax.swing.JDialog getCarDialog() {
        return carDialog;
    }
    
    public javax.swing.JDialog getExtensionDlg() {
        return extensionDlg;
    }
    
    public javax.swing.JDialog getStaffDialog() {
        return staffDialog;
    }
    
    public org.jdesktop.swingx.JXTable getRentalTbl() {
        return rentalTbl;
    }
    
    public void setRentalsTbl(org.jdesktop.swingx.JXTable rentalsTbl) {
        this.rentalTbl = rentalsTbl;
    }
    
    public org.jdesktop.swingx.JXTable getClassTbl() {
        return carClassTbl;
    }
    
    public org.jdesktop.swingx.JXTable getCarTbl() {
        return carTbl;
    }
    
    public javax.swing.JTextField getRentalRefCodeTxt() {
        return rentalRefCodeTxt;
    }
    
    public javax.swing.JTextField getRentalSurnameTxt() {
        return rentalSurnameTxt;
    }
    
    public javax.swing.JButton getRentalClearBtn() {
        return rentalClearBtn;
    }
    
    public javax.swing.JButton getRentalDeleteBtn() {
        return rentalDeleteBtn;
    }
    
    public javax.swing.JButton getCarAddBtn() {
        return carAddBtn;
    }
    
    public javax.swing.JTextField getCarBrandTxt() {
        return carBrandTxt;
    }
    
    public javax.swing.JComboBox getCarClassCb() {
        return carClassCb;
    }
    
    public javax.swing.JButton getCarClearBtn() {
        return carClearBtn;
    }
    
    public javax.swing.JTextField getCarColorTxt() {
        return carColorTxt;
    }
    
    public javax.swing.JTextField getCarModelTxt() {
        return carModelTxt;
    }
    
    public javax.swing.JTextField getCarPlateTxt() {
        return carPlateTxt;
    }
    
    public javax.swing.JComboBox getCarStatusCB() {
        return carStatusCB;
    }
    
    public javax.swing.JTextField getCarYearTxt() {
        return carYearTxt;
    }
    
    public javax.swing.JButton getCarClassAddBtn() {
        return carClassAddBtn;
    }
    
    public javax.swing.JButton getCarClassClearBtn() {
        return carClassClearBtn;
    }
    
    public javax.swing.JTextField getCarClassDisplayTxt() {
        return carClassDisplayTxt;
    }
    
    public javax.swing.JTextField getCarClassNameTxt() {
        return carClassNameTxt;
    }            
}
