/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StaffView.java
 *
 * Created on Mar 21, 2012, 2:29:56 PM
 */
package oscar.view;

import oscar.persistance.AbstractView;

/**
 *
 * @author schiodin
 */
public class StaffView extends AbstractView{

    /** Creates new form StaffView */
    public StaffView() {
        initComponents();
        //this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        extensionDlg = new javax.swing.JDialog();
        oldDateLbl = new javax.swing.JLabel();
        oldDateDP = new org.jdesktop.swingx.JXDatePicker();
        newDateLbl = new javax.swing.JLabel();
        newDateDP = new org.jdesktop.swingx.JXDatePicker();
        Extendsbtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        tabPanel = new javax.swing.JTabbedPane();
        hirePanel = new javax.swing.JPanel();
        hireBtn = new javax.swing.JButton();
        personPanel = new javax.swing.JPanel();
        personLoadBtn = new javax.swing.JButton();
        nameLbl = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        surnameLbl = new javax.swing.JLabel();
        surnameTxt = new javax.swing.JTextField();
        dateOfBirthLbl = new javax.swing.JLabel();
        dateOfBirthDP = new org.jdesktop.swingx.JXDatePicker();
        emailLbl = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        phoneLbl = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        addressLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTxt = new javax.swing.JTextArea();
        carPanel = new javax.swing.JPanel();
        fromLbl = new javax.swing.JLabel();
        fromDP = new org.jdesktop.swingx.JXDatePicker();
        toLbl = new javax.swing.JLabel();
        toDP = new org.jdesktop.swingx.JXDatePicker();
        classLbl = new javax.swing.JLabel();
        classCB = new javax.swing.JComboBox();
        chauffeuredCB = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        carTbl = new org.jdesktop.swingx.JXTable();
        refCodeLbl = new javax.swing.JLabel();
        refCodeTxt = new javax.swing.JTextField();
        refCodeSearchBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        chauffeuredCB1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        returnPanel = new javax.swing.JPanel();
        carSearchPanel = new javax.swing.JPanel();
        refCodeLbl2 = new javax.swing.JLabel();
        surnameLbl2 = new javax.swing.JLabel();
        plateLbl = new javax.swing.JLabel();
        refCodeTxt2 = new javax.swing.JTextField();
        surnameTxt2 = new javax.swing.JTextField();
        plateTxt2 = new javax.swing.JTextField();
        clearBtn3 = new javax.swing.JButton();
        returnBtn = new javax.swing.JButton();
        extendsBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        usernameLbl = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(StaffView.class);
        extensionDlg.setTitle(resourceMap.getString("extensionDlg.title")); // NOI18N
        extensionDlg.setAlwaysOnTop(true);
        extensionDlg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        extensionDlg.setIconImage(null);
        extensionDlg.setMinimumSize(new java.awt.Dimension(281, 200));
        extensionDlg.setModal(true);
        extensionDlg.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        extensionDlg.setName("extensionDlg"); // NOI18N
        extensionDlg.setResizable(false);

        oldDateLbl.setText(resourceMap.getString("oldDateLbl.text")); // NOI18N
        oldDateLbl.setName("oldDateLbl"); // NOI18N

        oldDateDP.setEditable(false);
        oldDateDP.setName("oldDateDP"); // NOI18N

        newDateLbl.setText(resourceMap.getString("newDateLbl.text")); // NOI18N
        newDateLbl.setName("newDateLbl"); // NOI18N

        newDateDP.setName("newDateDP"); // NOI18N

        Extendsbtn.setIcon(resourceMap.getIcon("Extendsbtn.icon")); // NOI18N
        Extendsbtn.setText(resourceMap.getString("Extendsbtn.text")); // NOI18N
        Extendsbtn.setName("Extendsbtn"); // NOI18N

        javax.swing.GroupLayout extensionDlgLayout = new javax.swing.GroupLayout(extensionDlg.getContentPane());
        extensionDlg.getContentPane().setLayout(extensionDlgLayout);
        extensionDlgLayout.setHorizontalGroup(
            extensionDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(extensionDlgLayout.createSequentialGroup()
                .addGroup(extensionDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, extensionDlgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(extensionDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oldDateLbl)
                            .addComponent(newDateLbl))
                        .addGap(23, 23, 23)
                        .addGroup(extensionDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newDateDP, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oldDateDP, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                    .addGroup(extensionDlgLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(Extendsbtn)))
                .addContainerGap())
        );
        extensionDlgLayout.setVerticalGroup(
            extensionDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(extensionDlgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(extensionDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldDateLbl)
                    .addComponent(oldDateDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(extensionDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newDateLbl)
                    .addComponent(newDateDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Extendsbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(resourceMap.getString("Staff.title")); // NOI18N
        setName("Staff"); // NOI18N

        logoutBtn.setIcon(resourceMap.getIcon("logoutBtn.icon")); // NOI18N
        logoutBtn.setText(resourceMap.getString("logoutBtn.text")); // NOI18N
        logoutBtn.setName("logoutBtn"); // NOI18N

        tabPanel.setName("tabPanel"); // NOI18N

        hirePanel.setName("hirePanel"); // NOI18N

        hireBtn.setIcon(resourceMap.getIcon("hireBtn.icon")); // NOI18N
        hireBtn.setText(resourceMap.getString("hireBtn.text")); // NOI18N
        hireBtn.setName("hireBtn"); // NOI18N

        personPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        personPanel.setName("personPanel"); // NOI18N

        personLoadBtn.setIcon(resourceMap.getIcon("personLoadBtn.icon")); // NOI18N
        personLoadBtn.setText(resourceMap.getString("personLoadBtn.text")); // NOI18N
        personLoadBtn.setName("personLoadBtn"); // NOI18N

        nameLbl.setText(resourceMap.getString("nameLbl.text")); // NOI18N
        nameLbl.setName("nameLbl"); // NOI18N

        nameTxt.setText(resourceMap.getString("nameTxt.text")); // NOI18N
        nameTxt.setName("nameTxt"); // NOI18N

        surnameLbl.setText(resourceMap.getString("surnameLbl.text")); // NOI18N
        surnameLbl.setName("surnameLbl"); // NOI18N

        surnameTxt.setText(resourceMap.getString("surnameTxt.text")); // NOI18N
        surnameTxt.setName("surnameTxt"); // NOI18N

        dateOfBirthLbl.setText(resourceMap.getString("dateOfBirthLbl.text")); // NOI18N
        dateOfBirthLbl.setName("dateOfBirthLbl"); // NOI18N

        dateOfBirthDP.setName("dateOfBirthDP"); // NOI18N

        emailLbl.setText(resourceMap.getString("emailLbl.text")); // NOI18N
        emailLbl.setName("emailLbl"); // NOI18N

        emailTxt.setText(resourceMap.getString("emailTxt.text")); // NOI18N
        emailTxt.setName("emailTxt"); // NOI18N

        phoneLbl.setText(resourceMap.getString("phoneLbl.text")); // NOI18N
        phoneLbl.setName("phoneLbl"); // NOI18N

        phoneTxt.setText(resourceMap.getString("phoneTxt.text")); // NOI18N
        phoneTxt.setName("phoneTxt"); // NOI18N

        addressLbl.setText(resourceMap.getString("addressLbl.text")); // NOI18N
        addressLbl.setName("addressLbl"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        addressTxt.setColumns(20);
        addressTxt.setRows(5);
        addressTxt.setName("addressTxt"); // NOI18N
        jScrollPane1.setViewportView(addressTxt);

        javax.swing.GroupLayout personPanelLayout = new javax.swing.GroupLayout(personPanel);
        personPanel.setLayout(personPanelLayout);
        personPanelLayout.setHorizontalGroup(
            personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(personLoadBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addGroup(personPanelLayout.createSequentialGroup()
                        .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLbl)
                            .addComponent(surnameLbl)
                            .addComponent(emailLbl)
                            .addComponent(phoneLbl)
                            .addComponent(addressLbl)
                            .addComponent(dateOfBirthLbl))
                        .addGap(35, 35, 35)
                        .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(nameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(surnameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(dateOfBirthDP, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(phoneTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(emailTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))))
                .addContainerGap())
        );
        personPanelLayout.setVerticalGroup(
            personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(personLoadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surnameLbl)
                    .addComponent(surnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateOfBirthLbl)
                    .addComponent(dateOfBirthDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLbl)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLbl)
                    .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressLbl)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
                .addContainerGap())
        );

        carPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        carPanel.setName("carPanel"); // NOI18N

        fromLbl.setText(resourceMap.getString("fromLbl.text")); // NOI18N
        fromLbl.setName("fromLbl"); // NOI18N

        fromDP.setName("fromDP"); // NOI18N

        toLbl.setText(resourceMap.getString("toLbl.text")); // NOI18N
        toLbl.setName("toLbl"); // NOI18N

        toDP.setName("toDP"); // NOI18N

        classLbl.setText(resourceMap.getString("classLbl.text")); // NOI18N
        classLbl.setName("classLbl"); // NOI18N

        classCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        classCB.setName("classCB"); // NOI18N

        chauffeuredCB.setText(resourceMap.getString("chauffeuredCB.text")); // NOI18N
        chauffeuredCB.setName("chauffeuredCB"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        carTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        carTbl.setName("carTbl"); // NOI18N
        jScrollPane2.setViewportView(carTbl);

        refCodeLbl.setText(resourceMap.getString("refCodeLbl.text")); // NOI18N
        refCodeLbl.setName("refCodeLbl"); // NOI18N

        refCodeTxt.setName("refCodeTxt"); // NOI18N

        refCodeSearchBtn.setIcon(resourceMap.getIcon("refCodeSearchBtn.icon")); // NOI18N
        refCodeSearchBtn.setText(resourceMap.getString("refCodeSearchBtn.text")); // NOI18N
        refCodeSearchBtn.setName("refCodeSearchBtn"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        chauffeuredCB1.setText(resourceMap.getString("chauffeuredCB1.text")); // NOI18N
        chauffeuredCB1.setName("chauffeuredCB1"); // NOI18N

        javax.swing.GroupLayout carPanelLayout = new javax.swing.GroupLayout(carPanel);
        carPanel.setLayout(carPanelLayout);
        carPanelLayout.setHorizontalGroup(
            carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(refCodeLbl)
                .addGap(18, 18, 18)
                .addComponent(refCodeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(refCodeSearchBtn)
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
            .addGroup(carPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(carPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE))
                    .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, carPanelLayout.createSequentialGroup()
                            .addComponent(toLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(toDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, carPanelLayout.createSequentialGroup()
                            .addComponent(fromLbl)
                            .addGap(18, 18, 18)
                            .addComponent(fromDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(carPanelLayout.createSequentialGroup()
                        .addComponent(classLbl)
                        .addGap(18, 18, 18)
                        .addComponent(classCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chauffeuredCB)
                        .addGap(18, 18, 18)
                        .addComponent(chauffeuredCB1)))
                .addContainerGap())
        );
        carPanelLayout.setVerticalGroup(
            carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refCodeSearchBtn)
                    .addComponent(refCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refCodeLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromLbl)
                    .addComponent(fromDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toLbl)
                    .addComponent(toDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classLbl)
                    .addComponent(classCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chauffeuredCB)
                    .addComponent(chauffeuredCB1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setIcon(resourceMap.getIcon("jButton1.icon")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        javax.swing.GroupLayout hirePanelLayout = new javax.swing.GroupLayout(hirePanel);
        hirePanel.setLayout(hirePanelLayout);
        hirePanelLayout.setHorizontalGroup(
            hirePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hirePanelLayout.createSequentialGroup()
                .addGroup(hirePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hirePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(personPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(hirePanelLayout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(hireBtn)))
                .addContainerGap())
        );
        hirePanelLayout.setVerticalGroup(
            hirePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hirePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hirePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(personPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(hirePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hireBtn)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        tabPanel.addTab(resourceMap.getString("hirePanel.TabConstraints.tabTitle"), hirePanel); // NOI18N

        returnPanel.setName("returnPanel"); // NOI18N

        carSearchPanel.setName("carSearchPanel"); // NOI18N

        refCodeLbl2.setText(resourceMap.getString("refCodeLbl2.text")); // NOI18N
        refCodeLbl2.setName("refCodeLbl2"); // NOI18N

        surnameLbl2.setText(resourceMap.getString("surnameLbl2.text")); // NOI18N
        surnameLbl2.setName("surnameLbl2"); // NOI18N

        plateLbl.setText(resourceMap.getString("plateLbl.text")); // NOI18N
        plateLbl.setName("plateLbl"); // NOI18N

        refCodeTxt2.setName("refCodeTxt2"); // NOI18N

        surnameTxt2.setName("surnameTxt2"); // NOI18N

        plateTxt2.setName("plateTxt2"); // NOI18N

        clearBtn3.setIcon(resourceMap.getIcon("clearBtn3.icon")); // NOI18N
        clearBtn3.setText(resourceMap.getString("clearBtn3.text")); // NOI18N
        clearBtn3.setName("clearBtn3"); // NOI18N

        returnBtn.setIcon(resourceMap.getIcon("returnBtn.icon")); // NOI18N
        returnBtn.setText(resourceMap.getString("returnBtn.text")); // NOI18N
        returnBtn.setName("returnBtn"); // NOI18N

        extendsBtn.setIcon(resourceMap.getIcon("extendsBtn.icon")); // NOI18N
        extendsBtn.setText(resourceMap.getString("extendsBtn.text")); // NOI18N
        extendsBtn.setName("extendsBtn"); // NOI18N
        extendsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extendsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout carSearchPanelLayout = new javax.swing.GroupLayout(carSearchPanel);
        carSearchPanel.setLayout(carSearchPanelLayout);
        carSearchPanelLayout.setHorizontalGroup(
            carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carSearchPanelLayout.createSequentialGroup()
                .addGroup(carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(carSearchPanelLayout.createSequentialGroup()
                        .addGroup(carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(surnameLbl2)
                            .addComponent(refCodeLbl2)
                            .addComponent(plateLbl))
                        .addGap(18, 18, 18)
                        .addGroup(carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plateTxt2, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(surnameTxt2, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(refCodeTxt2, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)))
                    .addComponent(clearBtn3)
                    .addComponent(returnBtn)
                    .addComponent(extendsBtn))
                .addContainerGap())
        );
        carSearchPanelLayout.setVerticalGroup(
            carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carSearchPanelLayout.createSequentialGroup()
                .addGroup(carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refCodeLbl2)
                    .addComponent(refCodeTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surnameLbl2)
                    .addComponent(surnameTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plateLbl)
                    .addComponent(plateTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(clearBtn3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(extendsBtn))
        );

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jXTable1.setName("jXTable1"); // NOI18N
        jScrollPane3.setViewportView(jXTable1);

        javax.swing.GroupLayout returnPanelLayout = new javax.swing.GroupLayout(returnPanel);
        returnPanel.setLayout(returnPanelLayout);
        returnPanelLayout.setHorizontalGroup(
            returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(carSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                .addContainerGap())
        );
        returnPanelLayout.setVerticalGroup(
            returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                    .addComponent(carSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabPanel.addTab(resourceMap.getString("returnPanel.TabConstraints.tabTitle"), returnPanel); // NOI18N

        usernameLbl.setIcon(resourceMap.getIcon("usernameLbl.icon")); // NOI18N
        usernameLbl.setText(resourceMap.getString("usernameLbl.text")); // NOI18N
        usernameLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        usernameLbl.setName("usernameLbl"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(715, Short.MAX_VALUE)
                .addComponent(usernameLbl)
                .addGap(18, 18, 18)
                .addComponent(logoutBtn))
            .addComponent(tabPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 904, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutBtn)
                    .addComponent(usernameLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void extendsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extendsBtnActionPerformed
        extensionDlg.setVisible(true);
    }//GEN-LAST:event_extendsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new StaffView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Extendsbtn;
    private javax.swing.JLabel addressLbl;
    private javax.swing.JTextArea addressTxt;
    private javax.swing.JPanel carPanel;
    private javax.swing.JPanel carSearchPanel;
    private org.jdesktop.swingx.JXTable carTbl;
    private javax.swing.JCheckBox chauffeuredCB;
    private javax.swing.JCheckBox chauffeuredCB1;
    private javax.swing.JComboBox classCB;
    private javax.swing.JLabel classLbl;
    private javax.swing.JButton clearBtn3;
    private org.jdesktop.swingx.JXDatePicker dateOfBirthDP;
    private javax.swing.JLabel dateOfBirthLbl;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JButton extendsBtn;
    private javax.swing.JDialog extensionDlg;
    private org.jdesktop.swingx.JXDatePicker fromDP;
    private javax.swing.JLabel fromLbl;
    private javax.swing.JButton hireBtn;
    private javax.swing.JPanel hirePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private org.jdesktop.swingx.JXTable jXTable1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxt;
    private org.jdesktop.swingx.JXDatePicker newDateDP;
    private javax.swing.JLabel newDateLbl;
    private org.jdesktop.swingx.JXDatePicker oldDateDP;
    private javax.swing.JLabel oldDateLbl;
    private javax.swing.JButton personLoadBtn;
    private javax.swing.JPanel personPanel;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JLabel plateLbl;
    private javax.swing.JTextField plateTxt2;
    private javax.swing.JLabel refCodeLbl;
    private javax.swing.JLabel refCodeLbl2;
    private javax.swing.JButton refCodeSearchBtn;
    private javax.swing.JTextField refCodeTxt;
    private javax.swing.JTextField refCodeTxt2;
    private javax.swing.JButton returnBtn;
    private javax.swing.JPanel returnPanel;
    private javax.swing.JLabel surnameLbl;
    private javax.swing.JLabel surnameLbl2;
    private javax.swing.JTextField surnameTxt;
    private javax.swing.JTextField surnameTxt2;
    private javax.swing.JTabbedPane tabPanel;
    private org.jdesktop.swingx.JXDatePicker toDP;
    private javax.swing.JLabel toLbl;
    private javax.swing.JLabel usernameLbl;
    // End of variables declaration//GEN-END:variables
}
